"""The 12x16 font has one source, firmware/lib/graphics/font_12x16.txt (each glyph drawn in '#' and '.'), and
tools/font_12x16.py generates what uses it: the firmware's glyph table, character_patterns_12x16.inc, and the
emulator's, emulator/chips/font_12x16.h (for the FPGA's text mode), which are committed and must be current,
and the FPGA's font memory, generated by the FPGA builds.

Run from the repo root:  python3 -m unittest discover -s tools/tests -v
"""
import os
import sys
import unittest

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
sys.path.insert(0, os.path.join(ROOT, 'tools'))
import font_12x16  # noqa: E402

INC = os.path.join(ROOT, 'firmware', 'lib', 'graphics', 'character_patterns_12x16.inc')
HEADER = os.path.join(ROOT, 'emulator', 'chips', 'font_12x16.h')
BOX = 0x7F


class FontTest(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.glyphs = font_12x16.read_source()

    def test_every_printable_character_is_drawn_once_and_the_box(self):
        self.assertEqual(sorted(self.glyphs), list(range(32, 127)) + [BOX])

    def test_the_box_is_an_outline(self):
        """$7F, drawn for codes outside the font (the FPGA's text mode draws every code from $7F up so), so a
        stray one shows."""
        rows = self.glyphs[BOX]
        self.assertEqual(rows[1], '.##########.')
        self.assertEqual(rows[14], '.##########.')
        self.assertTrue(all(row == '.#........#.' for row in rows[2:14]))
        self.assertEqual({rows[0], rows[15]}, {'.' * 12})

    def test_glyphs_are_16_rows_of_12(self):
        for code, rows in self.glyphs.items():
            with self.subTest(chr(code)):
                self.assertEqual(len(rows), 16)
                self.assertTrue(all(len(row) == 12 and set(row) <= {'#', '.'} for row in rows))

    def test_the_committed_firmware_table_is_current(self):
        with open(INC) as f:
            self.assertEqual(f.read(), font_12x16.firmware_table(self.glyphs),
                             'run: python3 tools/font_12x16.py inc')

    def test_the_committed_emulator_header_is_current(self):
        with open(HEADER) as f:
            self.assertEqual(f.read(), font_12x16.emulator_header(self.glyphs),
                             'run: python3 tools/font_12x16.py h')

    def test_the_emulator_header_has_the_fpgas_columns(self):
        """font_12x16[code][column], as the FPGA's memory has them: '!' is a stem and a dot in columns 5 and 6,
        the stem wider at its top in columns 4 and 7."""
        header = font_12x16.emulator_header(self.glyphs)
        self.assertIn('static const uint16_t font_12x16[128][12] = {', header)
        self.assertIn("/* $21 '!' */ { 0x0000, 0x0000, 0x0000, 0x0000, 0x007C, 0x33FF, 0x33FF, 0x007C, 0x0000,", header)

    def test_the_fpga_memory_is_a_column_of_16_pixels_per_word(self):
        """Word (code << 4) | column holds the column's pixels, the top one in bit 0, as the firmware sends
        them: '!' is a stem in rows 0-9 and a dot in rows 12-13, in columns 5 and 6."""
        words = font_12x16.fpga_words(self.glyphs)
        self.assertEqual(len(words), 128 * 16)
        self.assertEqual(words[(ord('!') << 4) | 5], 0x33FF)
        self.assertEqual(words[(ord('!') << 4) | 12], 0)   # columns 12-15 are padding
        self.assertEqual(words[(ord(' ') << 4) | 5], 0)
        self.assertEqual(sum(words[:32 << 4]), 0)   # no glyphs below ' '
        self.assertEqual(words[(BOX << 4) | 1], 0x7FFE)   # the box's left side


if __name__ == '__main__':
    unittest.main()
