"""The 12x16 font comes from the original C font, firmware/fonts/font-12x16.c (its console_font_12x16 array):
its glyphs for $20-$FF, as they are (code page 437's: $7F a house, the line-drawing and accented characters
above). tools/font_12x16.py expands them into firmware/lib/graphics/font_12x16.txt (each glyph drawn in '#' and
'.', for viewing), and generates everything else from that: the firmware's glyph table ($20-$7F),
character_patterns_12x16.inc, and the FPGA's font memory (every code, the control codes blank: text mode drops
them), generated by the FPGA builds. The view and the table are committed, and must be current.

Run from the repo root:  python3 -m unittest discover -s tools/tests -v
"""
import os
import sys
import unittest

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
sys.path.insert(0, os.path.join(ROOT, 'tools'))
import font_12x16  # noqa: E402

INC = os.path.join(ROOT, 'firmware', 'lib', 'graphics', 'character_patterns_12x16.inc')
VIEW = os.path.join(ROOT, 'firmware', 'lib', 'graphics', 'font_12x16.txt')
DEL = 0x7F


class FontTest(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.glyphs = font_12x16.read_source()   # the committed view

    def test_every_code_from_space_up_is_drawn_once(self):
        self.assertEqual(sorted(self.glyphs), list(range(0x20, 0x100)))

    def test_the_c_font_is_read_from_its_array(self):
        """Its 256 glyphs, 16 rows of 2 bytes each, the leftmost pixel in the first byte's top bit (the comments
        beside the bytes, which show the same pixels, are ignored)."""
        glyphs = font_12x16.read_c_font()
        self.assertEqual(sorted(glyphs), list(range(256)))
        self.assertEqual(glyphs[ord('!')][0], '.....##.....')
        self.assertEqual(glyphs[ord('!')][15], '............')
        self.assertEqual(glyphs[1][0], '.....###....')   # its first row: 0x07, 0x00 (and a comment saying "hex=0x01")

    def test_the_font_is_the_c_fonts(self):
        """Every glyph as the C font has it: DEL ($7F) too, its house."""
        c_font = font_12x16.read_c_font()
        for code in range(0x20, 0x100):
            self.assertEqual(self.glyphs[code], c_font[code], hex(code))
        self.assertEqual(self.glyphs[DEL][4:8], ['.....##.....', '....####....', '...##..##...', '..##....##..'])

    def test_the_committed_view_is_current(self):
        with open(VIEW) as f:
            self.assertEqual(f.read(), font_12x16.view(font_12x16.build()), 'run: python3 tools/font_12x16.py')

    def test_glyphs_are_16_rows_of_12(self):
        for code, rows in self.glyphs.items():
            with self.subTest(chr(code)):
                self.assertEqual(len(rows), 16)
                self.assertTrue(all(len(row) == 12 and set(row) <= {'#', '.'} for row in rows))

    def test_the_committed_firmware_table_is_current(self):
        with open(INC) as f:
            self.assertEqual(f.read(), font_12x16.firmware_table(self.glyphs),
                             'run: python3 tools/font_12x16.py')
        self.assertIn('; 127 $7f DEL', font_12x16.firmware_table(self.glyphs).split('\n')[-2])   # $20-$7F only

    def test_the_fpga_memory_is_a_column_of_16_pixels_per_word(self):
        """Word (code << 4) | column holds the column's pixels, the top one in bit 0, as the firmware sends
        them: '!' is a stem in rows 0-9 and a dot in rows 12-13, in columns 5 and 6. Every code has its glyph
        but the control codes, which text mode never stores: they're blank."""
        words = font_12x16.fpga_words(self.glyphs)
        self.assertEqual(len(words), 256 * 16)
        self.assertEqual(words[(ord('!') << 4) | 5], 0x33FF)
        self.assertEqual(words[(ord('!') << 4) | 12], 0)   # columns 12-15 are padding
        self.assertEqual(words[(ord(' ') << 4) | 5], 0)
        self.assertEqual(sum(words[:0x20 << 4]), 0)
        self.assertNotEqual(sum(words[0xB1 << 4:0xB2 << 4]), 0)   # a shade, from the top half


if __name__ == '__main__':
    unittest.main()
