"""Codegen for the Prog8 subset -> 6502 assembly.

Phase 1 targets a syntax that is a strict subset of both vasm6502_oldstyle
and asm17, so we can iterate with vasm during development and switch
to asm17-only once the self-hosting path is set up.

Generated layout:

    .include base_config_wendy2c.inc
    DISPLAY_STRING_PARAM = $00
    .org <address>
    jmp p8s_main             ; entry sub (`start` for a main-block program)
    .include delay_routines.inc
    .include display_routines_4bit.inc
    .include display_string.inc

    ; ---- user code ----
    p8s_main:
        <body>
        rts                      ; main() falls through to halt loop
    <user subs...>

    ; ---- string pool ----
    p8c_str_0: .asciiz "..."
    p8c_str_1: .asciiz "..."
    ...

A `main { ... }` sub falls off the end into a `bra *` halt so the
emulator can dump the LCD on cycle cap (the on-target equivalent of
exit()).
"""
from __future__ import annotations

from .ast import (
    AddressOf, Assign, BinOp, Block, BoolLit, Break, Call, Cast, Continue, Defer,
    ExprStmt, For, Ident, If, Index, InlineAsm, IntLit, MemAt, Param,
    Program, Repeat, Return, StrLit, Sub, TUByteArray, TUWordArray, UnaryOp, VarDecl,
    When, WhenChoice, While, BOOL, BYTE, UBYTE, UWORD, type_from_name,
)


# Compiler-managed ZP scratch.
TMP0 = "$20"        # general byte temp 0 (for nested expression spill)
TMP1 = "$21"        # general byte temp 1
# Word spill slots for uword arithmetic; pairs of bytes (lo, hi).
WTMP0_LO = "$22"
WTMP1_LO = "$24"
PTR0_LO = "$26"   # indirect pointer for @() addressing
APTR_LO = "$28"   # indirect pointer for 16-bit array element addressing
PROLOGUE_WENDY2C = """\
; ---- generated by p8c -- DO NOT EDIT ----
; source: {source}
; target: wendy2c
  .include base_config_wendy2c.inc

DISPLAY_STRING_PARAM = $00              ; 2 bytes scratch (display_string ABI)
__p8c_tmp0 = {tmp0}                     ; codegen scratch (byte)
__p8c_tmp1 = {tmp1}                     ; codegen scratch (byte)
__p8c_wtmp0 = {wtmp0}                   ; codegen scratch (word, 2 bytes)
__p8c_wtmp1 = {wtmp1}                   ; codegen scratch (word, 2 bytes)
__p8c_ptr0  = {ptr0}                    ; indirect-Y pointer (2 bytes)
__p8c_aptr  = {aptr}                    ; array element pointer (2 bytes)

  .org ${addr:04x}
  jmp {entry}

  .include delay_routines.inc
  .include display_routines_4bit.inc
  .include display_string.inc
  .include display_hex.inc
"""

PROLOGUE_NMOS = """\
; ---- generated by p8c -- DO NOT EDIT ----
; source: {source}
; target: nmos (vasm builds a self-contained 6502 binary, reset vector
;               at $FFFC points to p8s_main; intended for the emulator's
;               nmos-default machine with file-I/O stubs at $F006-$F03C).

__p8c_tmp0 = {tmp0}                     ; codegen scratch (byte)
__p8c_tmp1 = {tmp1}                     ; codegen scratch (byte)
__p8c_wtmp0 = {wtmp0}                   ; codegen scratch (word)
__p8c_wtmp1 = {wtmp1}                   ; codegen scratch (word)
__p8c_ptr0  = {ptr0}                    ; indirect-Y pointer (2 bytes)
__p8c_aptr  = {aptr}                    ; array element pointer (2 bytes)

  .org ${addr:04x}
  jmp {entry}
"""

NMOS_EPILOGUE = """\
  ; ---- reset vector ----
  .org $FFFC
  .word {entry}
  .word $0000
"""


class CodeGenError(Exception):
    pass


class CodeGen:
    def __init__(self, prog: Program, source_path: str):
        self.prog = prog
        self.source_path = source_path
        self.out: list[str] = []

    def emit(self, line: str = "") -> None:
        self.out.append(line)

    def _array_elem_asm(self, el) -> str:
        """One array-initializer element as an asm operand for `.byte`/`.word`:
        an int literal -> its number; a string literal -> its pool label (the
        string's address); a const ident -> its folded value; a var/array
        ident or &name -> the symbol's label (its address)."""
        if isinstance(el, IntLit):
            return str(el.value)
        if isinstance(el, StrLit):
            return self._str_label(el)
        if isinstance(el, AddressOf):
            return el.sym.mangled if el.sym is not None else el.name
        if isinstance(el, Ident):
            if el.sym is not None and el.sym.kind == "const":
                return str(el.sym.const_value)
            if el.sym is not None:
                return el.sym.mangled
        raise CodeGenError(f"unsupported array initializer element: {el!r}")

    def _str_label(self, lit: StrLit) -> str:
        """Assign (lazily) and return a string literal's pool label.

        Labels are handed out on first reference during emission, which --
        because subs are emitted main-first -- matches the order p1 interns
        its string labels in its single codegen pass. This keeps the two
        compilers byte-identical without p1 needing a separate pre-pass.

        Identical string content is deduplicated: a literal whose value
        already appears in the pool reuses that label, so the pool holds
        each distinct string once. p1's intern_str_label does the same
        (compares pool bytes), so the two stay byte-identical.
        """
        if getattr(lit, "label", None) is not None:
            return lit.label
        for prior in self.prog.strings:
            if prior.value == lit.value:
                lit.label = prior.label
                return lit.label
        lit.label = f"p8c_str_{len(self.prog.strings)}"
        self.prog.strings.append(lit)
        return lit.label

    def generate(self) -> str:
        self.out.clear()
        self._mul_used = False
        self._strcmp_used = False
        # The entry is the `is_main` sub: `main` for the entry-body form, or
        # `start` for an upstream-style `main { ... }` namespace block.
        entry_sub = next((s for s in self.prog.subs if s.is_main), None)
        self._entry_mangled = entry_sub.mangled if entry_sub else "p8s_main"
        prologue = PROLOGUE_NMOS if self.prog.target == "nmos" else PROLOGUE_WENDY2C
        self.emit(prologue.format(
            source=self.source_path, addr=self.prog.address, entry=self._entry_mangled,
            tmp0=TMP0, tmp1=TMP1, wtmp0=WTMP0_LO, wtmp1=WTMP1_LO,
            ptr0=PTR0_LO, aptr=APTR_LO,
        ))
        # Emit ZP variable address bindings before any code so labels
        # resolve regardless of declaration order. Arrays are emitted
        # later as labeled .byte blocks (main memory, not ZP).
        scalar_vars = [s for s in self.prog.all_vars
                       if s.kind not in ("array", "struct_instance",
                                          "struct_array")]
        array_vars = [s for s in self.prog.all_vars if s.kind == "array"]
        struct_vars = [s for s in self.prog.all_vars if s.kind == "struct_instance"]
        struct_arrays = [s for s in self.prog.all_vars if s.kind == "struct_array"]
        # Scalars with a ZP address get a zero-page binding; scalars that
        # overflowed ZP (address is None) are emitted as labeled main-
        # memory reservations further down (memvars) and referenced by
        # label (absolute addressing) -- `lda <mangled>` works for both.
        zp_scalars = [s for s in scalar_vars if s.address is not None]
        mem_scalars = [s for s in scalar_vars if s.address is None]
        if zp_scalars:
            self.emit("; ---- ZP variable allocations ----")
            for sym in zp_scalars:
                self.emit(f"{sym.mangled} = ${sym.address:02x}")
            self.emit("")
        # main() must be emitted first (the prologue's JMP points at it).
        subs_sorted = sorted(self.prog.subs, key=lambda s: 0 if s.is_main else 1)
        for s in subs_sorted:
            self._emit_sub(s)
        if self._mul_used:
            self.emit("")
            self.emit("; ---- runtime: ubyte * ubyte -> A ----")
            self.emit("__p8c_mul_u8:")
            self.emit("  lda #0")
            self.emit("  ldx #8")
            self.emit(".__mul_loop:")
            self.emit("  lsr __p8c_tmp1")
            self.emit("  bcc .__mul_skip")
            self.emit("  clc")
            self.emit("  adc __p8c_tmp0")
            self.emit(".__mul_skip:")
            self.emit("  asl __p8c_tmp0")
            self.emit("  dex")
            self.emit("  bne .__mul_loop")
            self.emit("  rts")
        if self._strcmp_used:
            self.emit("")
            self.emit("__p8c_strcmp:")
            self.emit("  ldy #0")
            self.emit(".__sc_loop:")
            self.emit("  lda (__p8c_wtmp0),y")
            self.emit("  cmp (__p8c_wtmp1),y")
            self.emit("  bne .__sc_diff")
            self.emit("  lda (__p8c_wtmp0),y")    # equal bytes; at terminator?
            self.emit("  beq .__sc_eq")
            self.emit("  iny")
            self.emit("  bne .__sc_loop")
            self.emit(".__sc_eq:")
            self.emit("  lda #0")
            self.emit("  rts")
            self.emit(".__sc_diff:")
            self.emit("  bcc .__sc_less")
            self.emit("  lda #1")
            self.emit("  rts")
            self.emit(".__sc_less:")
            self.emit("  lda #$ff")
            self.emit("  rts")
        if array_vars:
            self.emit("")
            self.emit("; ---- arrays ----")
            for sym in array_vars:
                assert isinstance(sym.type, (TUByteArray, TUWordArray))
                init = getattr(sym, "init_lit", None)
                if isinstance(sym.type, TUWordArray):
                    # Split lo/hi byte storage (upstream @split model): two
                    # parallel byte arrays so `a[i]` is byte-indexed
                    # (lda a_lo,y / lda a_hi,y) with no 16-bit pointer math.
                    if init is not None:
                        elems = [self._array_elem_asm(el) for el in init.elements]
                        los = ["<" + v for v in elems]
                        his = [">" + v for v in elems]
                    else:
                        los = ["0"] * sym.type.size
                        his = ["0"] * sym.type.size
                    self.emit(f"{sym.mangled}_lo:")
                    self.emit("  .byte " + ", ".join(los))
                    self.emit(f"{sym.mangled}_hi:")
                    self.emit("  .byte " + ", ".join(his))
                else:
                    self.emit(f"{sym.mangled}:")
                    if init is not None:
                        vals = [self._array_elem_asm(el) for el in init.elements]
                        self.emit("  .byte " + ", ".join(vals))
                    else:
                        self.emit("  .byte " + ", ".join(["0"] * sym.type.size))
        if mem_scalars:
            self.emit("")
            self.emit("; ---- scalars overflowed from ZP into main memory ----")
            for sym in mem_scalars:
                nbytes = 2 if sym.type is UWORD else 1
                self.emit(f"{sym.mangled}:")
                self.emit(f"  .byte " + ", ".join(["0"] * nbytes))
        if struct_vars:
            self.emit("")
            self.emit("; ---- struct instances ----")
            for sym in struct_vars:
                size = sym.struct_size                 # type: ignore[attr-defined]
                self.emit(f"{sym.mangled}:")
                self.emit(f"  .byte " + ", ".join(["0"] * size))
        if struct_arrays:
            self.emit("")
            self.emit("; ---- struct arrays ----")
            for sym in struct_arrays:
                total = sym.total_bytes               # type: ignore[attr-defined]
                self.emit(f"{sym.mangled}:")
                self.emit(f"  .byte " + ", ".join(["0"] * total))
        if self.prog.strings:
            self.emit("")
            self.emit("; ---- string pool ----")
            if self.prog.target == "nmos":
                # Park the read-only string pool above the emulator's I/O stub
                # routines (which end ~$F0B0) and below its argv window / ports,
                # freeing the low $0200..$F006 window entirely for code +
                # arenas. The binary still spans $0200..$FFFF (the reset vector
                # pins the top), so the load address is unchanged -- only the
                # pool's position within the image moves. See RESUME_NOTES.
                self.emit("  .org $F0C0")
            for lit in self.prog.strings:
                self.emit(f"{lit.label}:")
                escaped = self._escape(lit.value)
                self.emit(f'  .byte {escaped}, 0')
        if self.prog.target == "nmos":
            self.emit("")
            self.emit(NMOS_EPILOGUE.format(entry=self._entry_mangled))
        return "\n".join(self.out) + "\n"

    def _escape(self, s: str) -> str:
        """Turn a Python string into a `.byte` list compatible with both
        asm17 and vasm without depending on -esc."""
        parts: list[str] = []
        run: list[str] = []

        def flush():
            if run:
                parts.append('"' + "".join(run) + '"')
                run.clear()

        for ch in s:
            o = ord(ch)
            if 0x20 <= o < 0x7F and ch not in ('"', '\\'):
                run.append(ch)
            else:
                flush()
                parts.append(f"${o:02x}")
        flush()
        if not parts:
            parts.append("0")
        return ", ".join(parts)

    def _emit_sub(self, s: Sub) -> None:
        if s.is_asmsub:
            # `asmsub name(..) = $ADDR` / `extsub` are pure declarations (no
            # body). The register-ABI form with an inline %asm body emits a
            # label + the raw asm (no static-param prologue: args arrived in
            # registers, and the body has its own rts).
            if s.asm_target is None and s.body.stmts:
                self.emit("")
                self.emit(f"; ---- asmsub {s.name} ----")
                self.emit(f"{s.mangled}:")
                for st in s.body.stmts:
                    if not isinstance(st, InlineAsm):
                        raise CodeGenError(
                            f"asmsub {s.name!r} body must be a single %asm block")
                    for line in st.text.splitlines():
                        self.emit("  " + line)
            return
        if s.is_inline:
            return       # body is spliced at each call site
        self.emit("")
        self.emit(f"; ---- sub {s.name} ----")
        self.emit(f"{s.mangled}:")
        # Each sub gets its own "return jumps here" label so `return X`
        # can load the value and jmp here without duplicating epilogue
        # code at every return site.
        self._loop_break_stack: list[str] = []
        self._loop_cont_stack: list[str] = []
        self._label_id = 0
        self._current_sub = s
        self._return_label = f".L{s.mangled}_ret"
        # Track defers registered in this sub: LIFO list of body stmts.
        # When a `return` (or fall-through) is encountered, codegen
        # emits the registered defer bodies in REVERSE registration
        # order, then jumps to the per-sub epilogue label.
        self._defer_stack: list = []
        # Module-var initializers run at the top of main().
        if s.is_main:
            for vd in self.prog.module_vars:
                # const decls are compile-time only; the value is folded
                # at every use site, no runtime store needed. array initializers
                # are emitted statically in the `; ---- arrays ----` data block.
                if vd.sym is None or vd.sym.kind in ("const", "array"):
                    continue
                if vd.init is None:
                    continue
                if vd.sym.type is UBYTE:
                    self._emit_byte_expr_into_a(vd.init)
                    self.emit(f"  sta {vd.sym.mangled}")
                else:
                    self._emit_word_expr_into_ay(vd.init)
                    self.emit(f"  sta {vd.sym.mangled}")
                    self.emit(f"  sty {vd.sym.mangled}+1")
        self._emit_block(s.body)
        # Fall-through to return path: emit defers in LIFO order before
        # the epilogue label (so the epilogue itself stays just one
        # instruction).
        for ds in reversed(self._defer_stack):
            self._emit_stmt(ds)
        self.emit(f"{self._return_label}:")
        if s.is_main:
            if self.prog.target == "nmos":
                # exit(0) -- nmos has the stub at $F00F.
                self.emit("  lda #$00")
                self.emit("  jsr $f00f")
                self.emit("  brk")
            else:
                # wendy2c has no exit syscall; halt and let the emulator's
                # --cycle-cap dump the LCD.
                self.emit(f".Lhalt_{s.mangled}:")
                self.emit(f"  bra .Lhalt_{s.mangled}")
        else:
            self.emit("  rts")
        self._current_sub = None

    def _new_label(self, prefix: str) -> str:
        lid = self._label_id
        self._label_id += 1
        return f".L{prefix}_{lid}"

    def _emit_block(self, blk: Block) -> None:
        for st in blk.stmts:
            self._emit_stmt(st)

    def _emit_stmt(self, st) -> None:
        if isinstance(st, ExprStmt):
            self._emit_expr(st.expr, drop_value=True)
        elif isinstance(st, InlineAsm):
            for line in st.text.splitlines():
                self.emit("  " + line)
        elif isinstance(st, VarDecl):
            # Declaration is purely a storage reservation (handled at
            # the top of the .s by `<mangled> = $XX`). If there's an
            # initializer, lower it to a store.
            if st.init is not None:
                if st.sym.type is UBYTE:
                    self._emit_byte_expr_into_a(st.init)
                    self.emit(f"  sta {st.sym.mangled}")
                else:  # UWORD
                    self._emit_word_expr_into_ay(st.init)
                    self.emit(f"  sta {st.sym.mangled}")
                    self.emit(f"  sty {st.sym.mangled}+1")
        elif isinstance(st, Assign):
            self._emit_assign(st)
        elif isinstance(st, If):
            self._emit_if(st)
        elif isinstance(st, While):
            self._emit_while(st)
        elif isinstance(st, Repeat):
            self._emit_repeat(st)
        elif isinstance(st, When):
            self._emit_when(st)
        elif isinstance(st, For):
            self._emit_for(st)
        elif isinstance(st, Break):
            if not self._loop_break_stack:
                raise CodeGenError(
                    f"{st.loc.file}:{st.loc.line}:{st.loc.col}: `break` outside loop"
                )
            self.emit(f"  jmp {self._loop_break_stack[-1]}")
        elif isinstance(st, Continue):
            if not self._loop_cont_stack:
                raise CodeGenError(
                    f"{st.loc.file}:{st.loc.line}:{st.loc.col}: `continue` outside loop"
                )
            self.emit(f"  jmp {self._loop_cont_stack[-1]}")
        elif isinstance(st, Defer):
            # Push: the body will be re-emitted at every return path.
            self._defer_stack.append(st.stmt)
        elif isinstance(st, Return):
            cur = self._current_sub
            ret_t = type_from_name(cur.return_type_name)
            # Emit defers in LIFO order BEFORE evaluating the return
            # value? Upstream Prog8 says defers run "after the return
            # expression has been computed but before the actual jump".
            # The cleanest is: evaluate return value, save to scratch,
            # run defers (which can mutate state but the return value
            # is already captured), restore, jump to epilogue.
            if st.value is not None:
                if ret_t is UBYTE or ret_t is BYTE:
                    self._emit_byte_expr_into_a(st.value)
                    self.emit("  pha")
                    for ds in reversed(self._defer_stack):
                        self._emit_stmt(ds)
                    self.emit("  pla")
                else:
                    self._emit_word_expr_into_ay(st.value)
                    self.emit("  pha")
                    self.emit("  tya")
                    self.emit("  pha")
                    for ds in reversed(self._defer_stack):
                        self._emit_stmt(ds)
                    self.emit("  pla")
                    self.emit("  tay")
                    self.emit("  pla")
            else:
                for ds in reversed(self._defer_stack):
                    self._emit_stmt(ds)
            self.emit(f"  jmp {self._return_label}")
        else:
            raise CodeGenError(f"codegen: unhandled stmt {type(st).__name__}")

    # ---- assignment ----

    def _emit_assign(self, a: Assign) -> None:
        # @(addr) = expr -- byte write to runtime-computed address.
        if isinstance(a.target, MemAt):
            # Fast path: literal address -> direct sta absolute.
            if isinstance(a.target.addr, IntLit):
                self._emit_byte_expr_into_a(a.rhs)
                addr = a.target.addr.value & 0xFFFF
                self.emit(f"  sta ${addr:04x}")
                return
            # General: eval rhs into A, save; eval addr into ptr0; sta (ptr0),y.
            self._emit_byte_expr_into_a(a.rhs)
            self.emit("  sta __p8c_tmp0")
            self._emit_word_expr_into_ay(a.target.addr)
            self.emit("  sta __p8c_ptr0")
            self.emit("  sty __p8c_ptr0+1")
            self.emit("  ldy #$00")
            self.emit("  lda __p8c_tmp0")
            self.emit("  sta (__p8c_ptr0),y")
            return
        # Array element write: arr[idx] = expr; also arr[idx].field.
        if isinstance(a.target, Index):
            tgt = a.target
            assert tgt.sym is not None
            if tgt.sym.kind == "struct_array":
                fo = getattr(tgt, "field_offset", 0)
                # We need to evaluate the RHS *and* compute the index in
                # Y. The index computation clobbers TMP0/TMP1 via the
                # mul helper, so park the RHS on the hardware stack
                # instead of in ZP scratch.
                if tgt.type is UWORD:
                    self._emit_word_expr_into_ay(a.rhs)
                    self.emit("  pha")       # low
                    self.emit("  tya")
                    self.emit("  pha")       # high
                    self._emit_struct_array_index_into_y(tgt)
                    self.emit("  pla")       # high back
                    self.emit(f"  sta {tgt.sym.mangled}+{fo + 1},y")
                    self.emit("  pla")       # low back
                    self.emit(f"  sta {tgt.sym.mangled}+{fo},y")
                else:
                    self._emit_byte_expr_into_a(a.rhs)
                    self.emit("  pha")
                    self._emit_struct_array_index_into_y(tgt)
                    self.emit("  pla")
                    self.emit(f"  sta {tgt.sym.mangled}+{fo},y")
                return
            # uword[] arr -- indexed word write (rhs widened to uword).
            if isinstance(tgt.sym.type, TUWordArray):
                # split lo/hi: byte-indexed store of the two halves.
                self._emit_word_expr_into_ay(a.rhs)
                self.emit("  pha")               # lo
                self.emit("  tya")
                self.emit("  pha")               # hi
                self._emit_word_expr_into_ay(tgt.index)
                self.emit("  tay")               # byte index -> Y
                self.emit("  pla")               # hi
                self.emit(f"  sta {tgt.sym.mangled}_hi,y")
                self.emit("  pla")               # lo
                self.emit(f"  sta {tgt.sym.mangled}_lo,y")
                return
            # ubyte[] arr -- simple indexed byte write (fast `,y` path).
            if self._array_fast_byte(tgt.sym, tgt.index):
                if isinstance(tgt.index, IntLit):
                    # constant index -> absolute store, no scratch/Y setup.
                    self._emit_byte_expr_into_a(a.rhs)
                    self.emit(f"  sta {tgt.sym.mangled}+{tgt.index.value & 0xFF}")
                    return
                self._emit_byte_expr_into_a(a.rhs)
                self.emit("  sta __p8c_tmp0")
                self._emit_byte_expr_into_a(tgt.index)
                self.emit("  tay")
                self.emit("  lda __p8c_tmp0")
                self.emit(f"  sta {tgt.sym.mangled},y")
                return
            # ubyte element, uword index (<=256 array): byte-index store,
            # truncating the index to its low byte.
            self._emit_byte_expr_into_a(a.rhs)
            self.emit("  pha")
            self._emit_word_expr_into_ay(tgt.index)
            self.emit("  tay")
            self.emit("  pla")
            self.emit(f"  sta {tgt.sym.mangled},y")
            return
        assert isinstance(a.target, Ident) and a.target.sym is not None
        sym = a.target.sym
        # Struct-instance write: `instance.field = expr`. sema marked
        # the Ident with field_offset and set its type to the field's type.
        if sym.kind == "struct_instance":
            off = getattr(a.target, "field_offset", 0)
            if a.target.type is UWORD:
                self._emit_word_expr_into_ay(a.rhs)
                self.emit(f"  sta {sym.mangled}+{off}")
                self.emit(f"  sty {sym.mangled}+{off + 1}")
            else:
                self._emit_byte_expr_into_a(a.rhs)
                self.emit(f"  sta {sym.mangled}+{off}")
            return
        if a.op == "=":
            if sym.type is UWORD:
                self._emit_word_expr_into_ay(a.rhs)
                self.emit(f"  sta {sym.mangled}")
                self.emit(f"  sty {sym.mangled}+1")
                return
            self._emit_byte_expr_into_a(a.rhs)
            self.emit(f"  sta {sym.mangled}")
            return
        # Augmented assignment: `x op= rhs` becomes `x = x op rhs`.
        if sym.type is UWORD:
            synthetic = BinOp(
                loc=a.loc, op=_aug_to_op(a.op),
                lhs=a.target, rhs=a.rhs, type=UWORD,
            )
            self._emit_word_expr_into_ay(synthetic)
            self.emit(f"  sta {sym.mangled}")
            self.emit(f"  sty {sym.mangled}+1")
            return
        # ubyte augmented: load LHS into A, apply op with RHS, store.
        self.emit(f"  lda {sym.mangled}")
        # Spill A to TMP1 so we can evaluate the RHS without losing it.
        # In most cases the RHS is a leaf and we don't need to spill, but
        # the generic path is simpler.
        if isinstance(a.rhs, (IntLit, Ident)):
            self._emit_byte_binop_leaf(_aug_to_op(a.op), a.rhs)
        else:
            # Generic: eval RHS into A first, save to TMP0, eval LHS into A,
            # then op with TMP0.
            self._emit_byte_expr_into_a(a.rhs)
            self.emit(f"  sta __p8c_tmp0")
            self.emit(f"  lda {sym.mangled}")
            self._emit_byte_binop_zp(_aug_to_op(a.op), "__p8c_tmp0")
        self.emit(f"  sta {sym.mangled}")

    # ---- control flow ----

    def _emit_if(self, n: If) -> None:
        else_label = self._new_label("else") if n.else_block else None
        end_label = self._new_label("endif")
        target = else_label if else_label else end_label
        self._emit_bool_test_branch_if_false(n.cond, target)
        self._emit_block(n.then_block)
        if else_label:
            self.emit(f"  jmp {end_label}")
            self.emit(f"{else_label}:")
            self._emit_block(n.else_block)
        self.emit(f"{end_label}:")

    def _emit_while(self, n: While) -> None:
        top_label = self._new_label("while_top")
        end_label = self._new_label("while_end")
        self._loop_break_stack.append(end_label)
        self._loop_cont_stack.append(top_label)
        self.emit(f"{top_label}:")
        self._emit_bool_test_branch_if_false(n.cond, end_label)
        self._emit_block(n.body)
        self.emit(f"  jmp {top_label}")
        self.emit(f"{end_label}:")
        self._loop_break_stack.pop()
        self._loop_cont_stack.pop()

    def _emit_repeat(self, n: Repeat) -> None:
        if n.count is None:
            # Forever loop -- still need break/continue targets.
            top = self._new_label("rep_top")
            end = self._new_label("rep_end")
            self._loop_break_stack.append(end)
            self._loop_cont_stack.append(top)
            self.emit(f"{top}:")
            self._emit_block(n.body)
            self.emit(f"  jmp {top}")
            self.emit(f"{end}:")
            self._loop_break_stack.pop()
            self._loop_cont_stack.pop()
            return
        # Counted: store count into a unique ZP slot allocated per loop
        # via the sema-assigned id. We model the slot as TMP1 + id-bias,
        # but since nested repeats need independent counters and we only
        # have a couple of compiler temps, we instead use the stack:
        #   eval count -> A
        #   pha                        ; push initial counter
        # top:
        #   evaluate body
        #   pla
        #   sec / sbc #1               ; decrement
        #   bne push_and_continue
        #   ; counter hit 0 -> exit
        #   jmp end
        # push_and_continue:
        #   pha
        #   jmp top
        # end:
        # NOTE: this is safe only if the body's stack effect is zero.
        # `break`/`continue` would skip the PLA, so we explicitly pop
        # before jumping out of the loop.
        top = self._new_label("rep_top")
        dec = self._new_label("rep_dec")
        end = self._new_label("rep_end")
        cont_label = dec  # `continue` jumps to the decrement step
        # break must pop the saved counter before exiting:
        break_label = self._new_label("rep_break")
        self._loop_break_stack.append(break_label)
        self._loop_cont_stack.append(cont_label)

        self._emit_byte_expr_into_a(n.count)
        self.emit("  pha")
        self.emit(f"{top}:")
        self._emit_block(n.body)
        self.emit(f"{dec}:")
        self.emit("  pla")
        self.emit("  sec")
        self.emit("  sbc #1")
        self._br("beq", end)
        self.emit("  pha")
        self.emit(f"  jmp {top}")
        self.emit(f"{break_label}:")
        self.emit("  pla")
        self.emit(f"{end}:")

        self._loop_break_stack.pop()
        self._loop_cont_stack.pop()

    def _emit_when(self, n: When) -> None:
        """when expr { v1, v2 -> body; else -> body }

        Lowered as a linear chain of comparisons. ubyte only for now;
        each arm's body, then jmp to end. else arm at the end runs if
        no arms match.
        """
        end = self._new_label("when_end")
        # Evaluate `expr` once; cache in TMP0.
        is_word = (n.expr.type is UWORD)
        if is_word:
            self._emit_word_into_wtmp(n.expr, "__p8c_wtmp0")
        else:
            self._emit_byte_expr_into_a(n.expr)
            self.emit("  sta __p8c_tmp0")
        for ch in n.choices:
            body_label = self._new_label("when_body")
            next_label = self._new_label("when_next")
            if not ch.values:
                # else arm: just emit body, fall through to end.
                self._emit_block(ch.body)
                self.emit(f"  jmp {end}")
                continue
            # Try each value; on match, jump to body_label.
            for v in ch.values:
                if is_word:
                    self._emit_word_into_wtmp(v, "__p8c_wtmp1")
                    self.emit("  lda __p8c_wtmp0+1")
                    self.emit("  cmp __p8c_wtmp1+1")
                    not_this = self._new_label("when_skip")
                    self._br("bne", not_this)
                    self.emit("  lda __p8c_wtmp0")
                    self.emit("  cmp __p8c_wtmp1")
                    self._br("beq", body_label)
                    self.emit(f"{not_this}:")
                else:
                    self._emit_byte_expr_into_a(v)
                    self.emit("  cmp __p8c_tmp0")
                    self._br("beq", body_label)
            # No value matched -- fall through to next arm.
            self.emit(f"  jmp {next_label}")
            self.emit(f"{body_label}:")
            self._emit_block(ch.body)
            self.emit(f"  jmp {end}")
            self.emit(f"{next_label}:")
        self.emit(f"{end}:")

    def _emit_for(self, n: For) -> None:
        """`for i in lo to hi` -- inclusive range, ubyte only.

        Lowered shape:
            <eval lo>; sta i
          top:
            <body>
            lda i; cmp #hi    (or cmp hi_addr for variable hi)
            beq end           ; i == hi -> last iteration already ran
            inc i
            jmp top
          end:
        """
        sym = n.sym
        assert sym is not None
        top = self._new_label("for_top")
        end = self._new_label("for_end")
        cont = self._new_label("for_cont")
        self._loop_break_stack.append(end)
        self._loop_cont_stack.append(cont)
        # Initialize loop var = lo.
        self._emit_byte_expr_into_a(n.lo)
        self.emit(f"  sta {sym.mangled}")
        self.emit(f"{top}:")
        self._emit_block(n.body)
        self.emit(f"{cont}:")
        # Compare against hi.
        self.emit(f"  lda {sym.mangled}")
        if isinstance(n.hi, IntLit):
            self.emit(f"  cmp #${n.hi.value & 0xFF:02x}")
        elif isinstance(n.hi, Ident):
            self.emit(f"  cmp {n.hi.sym.mangled}")
        else:
            # Evaluate hi into A (spilling i to a temp first).
            self.emit(f"  sta __p8c_tmp0")
            self._emit_byte_expr_into_a(n.hi)
            self.emit(f"  sta __p8c_tmp1")
            self.emit(f"  lda __p8c_tmp0")
            self.emit(f"  cmp __p8c_tmp1")
        self._br("beq", end)
        self.emit(f"  inc {sym.mangled}")
        self.emit(f"  jmp {top}")
        self.emit(f"{end}:")
        self._loop_break_stack.pop()
        self._loop_cont_stack.pop()

    def _emit_expr(self, e, drop_value: bool) -> None:
        if isinstance(e, Call):
            self._emit_call(e)
            return
        if drop_value and isinstance(e, (IntLit, BoolLit, StrLit, Ident)):
            return  # bare literal/var as a statement is a no-op
        # Bare expression used as a statement (rare) -- compute and discard.
        self._emit_byte_expr_into_a(e)

    # ---- uword expression codegen ----

    def _emit_word_expr_into_ay(self, e) -> None:
        """Evaluate a uword expression; result: low byte in A, high in Y.

        Widens ubyte to uword on the fly (high byte = 0).
        """
        if isinstance(e, IntLit):
            v = e.value & 0xFFFF
            self.emit(f"  lda #${v & 0xFF:02x}")
            self.emit(f"  ldy #${(v >> 8) & 0xFF:02x}")
            return
        if isinstance(e, StrLit):
            # A string literal is a uword: the address of its pool label
            # (low byte in A, high in Y). The label is interned lazily here.
            lbl = self._str_label(e)
            self.emit(f"  lda #<{lbl}")
            self.emit(f"  ldy #>{lbl}")
            return
        if isinstance(e, Ident):
            assert e.sym is not None
            if e.sym.kind == "const":
                v = e.sym.const_value & 0xFFFF
                self.emit(f"  lda #${v & 0xFF:02x}")
                self.emit(f"  ldy #${(v >> 8) & 0xFF:02x}")
                return
            if e.sym.kind == "struct_instance":
                off = getattr(e, "field_offset", 0)
                self.emit(f"  lda {e.sym.mangled}+{off}")
                self.emit(f"  ldy {e.sym.mangled}+{off + 1}")
                return
            if e.sym.type is UWORD:
                self.emit(f"  lda {e.sym.mangled}")
                self.emit(f"  ldy {e.sym.mangled}+1")
                return
            if e.sym.type in (UBYTE, BYTE):
                self.emit(f"  lda {e.sym.mangled}")
                self.emit(f"  ldy #$00")
                return
        if isinstance(e, AddressOf):
            assert e.sym is not None
            # For ZP var (kind="var"): immediate address; high byte = 0.
            # For array (kind="array"): label reference.
            if e.sym.kind == "var":
                self.emit(f"  lda #<{e.sym.mangled}")
                self.emit(f"  ldy #>{e.sym.mangled}")
            else:
                self.emit(f"  lda #<{e.sym.mangled}")
                self.emit(f"  ldy #>{e.sym.mangled}")
            return
        if isinstance(e, Index):
            assert e.sym is not None
            if e.sym.kind == "struct_array":
                fo = getattr(e, "field_offset", 0)
                self._emit_struct_array_index_into_y(e)
                # Y already holds i*size; need to load both bytes.
                # Save Y so the high-byte load can use Y+1; we use
                # absolute,Y twice with adjacent offsets.
                self.emit(f"  lda {e.sym.mangled}+{fo + 1},y")
                self.emit("  pha")
                self.emit(f"  lda {e.sym.mangled}+{fo},y")
                self.emit("  tax")
                self.emit("  pla")
                self.emit("  tay")
                self.emit("  txa")
                return
            if isinstance(e.sym.type, TUWordArray):
                # split lo/hi: byte-indexed load of the two halves.
                self._emit_word_expr_into_ay(e.index)   # index -> A:Y
                self.emit("  tay")                       # byte index -> Y
                self.emit(f"  lda {e.sym.mangled}_lo,y")
                self.emit("  pha")
                self.emit(f"  lda {e.sym.mangled}_hi,y")
                self.emit("  tay")
                self.emit("  pla")                  # lo -> A, hi in Y
                return
            # ubyte array element widened to uword (high byte = 0).
            if self._array_fast_byte(e.sym, e.index):
                self._emit_byte_expr_into_a(e.index)
                self.emit("  tay")
                self.emit(f"  lda {e.sym.mangled},y")
                self.emit("  ldy #$00")
                return
            # ubyte element, uword index (<=256): byte-index load, widened.
            self._emit_word_expr_into_ay(e.index)
            self.emit("  tay")
            self.emit(f"  lda {e.sym.mangled},y")
            self.emit("  ldy #$00")
            return
        if isinstance(e, Cast):
            if e.type is UWORD:
                # widen / identity to uword (handles ubyte->uword high=0).
                self._emit_word_expr_into_ay(e.operand)
            elif e.operand.type is UWORD:
                # narrow uword to (u)byte, then re-widen for word context.
                self._emit_word_expr_into_ay(e.operand)   # A=low, Y=high
                self.emit("  ldy #$00")                    # high byte = 0
            else:
                self._emit_byte_expr_into_a(e.operand)
                self.emit("  ldy #$00")
            return
        if isinstance(e, BinOp):
            self._emit_word_binop_into_ay(e)
            return
        if isinstance(e, UnaryOp):
            # Only ~ (bitwise complement) and - (negate) defined on uword.
            self._emit_word_expr_into_ay(e.operand)
            if e.op == "~":
                self.emit("  eor #$ff")
                self.emit("  sta __p8c_wtmp0")
                self.emit("  tya")
                self.emit("  eor #$ff")
                self.emit("  tay")
                self.emit("  lda __p8c_wtmp0")
                return
            if e.op == "-":
                # 16-bit negate: ~x + 1
                self.emit("  eor #$ff")
                self.emit("  sta __p8c_wtmp0")
                self.emit("  tya")
                self.emit("  eor #$ff")
                self.emit("  tay")
                self.emit("  lda __p8c_wtmp0")
                self.emit("  clc")
                self.emit("  adc #$01")
                self.emit("  bcc *+3")
                self.emit("  iny")
                return
            raise CodeGenError(f"unary {e.op!r} not supported on uword")
        if isinstance(e, Call):
            self._emit_call(e)
            # Builtins that return ubyte (peek) need widening; future
            # uword-returning calls leave Y set already.
            if e.sym is not None and e.sym.type is UBYTE:
                self.emit(f"  ldy #$00")
            return
        raise CodeGenError(
            f"codegen: cannot evaluate {type(e).__name__} as uword"
        )

    def _emit_word_into_wtmp(self, e, slot: str) -> None:
        """Evaluate uword expression e, store result at slot (low, high)."""
        self._emit_word_expr_into_ay(e)
        self.emit(f"  sta {slot}")
        self.emit(f"  sty {slot}+1")

    def _emit_word_operands(self, e: BinOp) -> None:
        """Evaluate both operands of a uword BinOp, leaving LHS in A:Y and
        RHS in __p8c_wtmp0 (lo, hi).

        LHS is held on the CPU stack while RHS is evaluated, so a RHS that
        itself reuses the wtmp scratch (a nested binop, a shift, a unary)
        cannot clobber the saved LHS. This is what makes nesting like
        `(v<<3) + (v<<1)` correct -- a fixed wtmp slot for LHS would be
        overwritten by the RHS shift. The hardware stack nests for free.
        """
        self._emit_word_expr_into_ay(e.lhs)
        self.emit("  pha")                  # LHS lo
        self.emit("  tya")
        self.emit("  pha")                  # LHS hi
        self._emit_word_expr_into_ay(e.rhs)
        self.emit("  sta __p8c_wtmp0")      # RHS lo
        self.emit("  sty __p8c_wtmp0+1")    # RHS hi
        self.emit("  pla")                  # LHS hi -> Y
        self.emit("  tay")
        self.emit("  pla")                  # LHS lo -> A

    def _emit_word_binop_into_ay(self, e: BinOp) -> None:
        """Compile a uword BinOp; result lo in A, hi in Y."""
        if e.op == "+":
            self._emit_word_operands(e)         # LHS -> A:Y, RHS -> wtmp0
            self.emit("  clc")
            self.emit("  adc __p8c_wtmp0")     # low + low
            self.emit("  pha")                  # save low result
            self.emit("  tya")                  # high LHS -> A
            self.emit("  adc __p8c_wtmp0+1")    # high + high + carry
            self.emit("  tay")                  # high result -> Y
            self.emit("  pla")                  # low result -> A
            return
        if e.op == "-":
            self._emit_word_operands(e)         # LHS -> A:Y, RHS -> wtmp0
            self.emit("  sec")
            self.emit("  sbc __p8c_wtmp0")
            self.emit("  pha")
            self.emit("  tya")
            self.emit("  sbc __p8c_wtmp0+1")
            self.emit("  tay")
            self.emit("  pla")
            return
        if e.op in ("&", "|", "^"):
            # Bitwise: low&low, high&high.
            self._emit_word_operands(e)         # LHS -> A:Y, RHS -> wtmp0
            op_mnem = {"&": "and", "|": "ora", "^": "eor"}[e.op]
            self.emit(f"  {op_mnem} __p8c_wtmp0")
            self.emit("  pha")
            self.emit("  tya")
            self.emit(f"  {op_mnem} __p8c_wtmp0+1")
            self.emit("  tay")
            self.emit("  pla")
            return
        if e.op in ("==", "!=", "<", "<=", ">", ">="):
            # Comparison returns 0/1 in A. uword-uword compare needs to
            # check high bytes first, then low.
            self._emit_word_cmp_into_a(e)
            return
        if e.op == "<<":
            self._emit_word_shl(e)
            return
        if e.op == ">>":
            self._emit_word_shr(e)
            return
        raise CodeGenError(f"uword op {e.op!r} not yet supported")

    def _emit_word_shl(self, e: BinOp) -> None:
        """uword << n. For n a const, unroll; otherwise loop. n is ubyte."""
        if isinstance(e.rhs, IntLit) and 0 <= e.rhs.value <= 16:
            n = e.rhs.value & 0x0F
            # Special case n == 8: high = low; low = 0.
            self._emit_word_expr_into_ay(e.lhs)
            if n == 0:
                return
            if n >= 8:
                # Shift by 8: high = low, low = 0; then shift remaining (n-8).
                self.emit("  tay")            # low -> Y (becomes new high)
                self.emit("  lda #$00")       # new low = 0
                for _ in range(n - 8):
                    # Shift A:Y left by 1: ASL low, ROL high.
                    self.emit("  asl a")
                    self.emit("  sta __p8c_wtmp0")
                    self.emit("  tya")
                    self.emit("  rol a")
                    self.emit("  tay")
                    self.emit("  lda __p8c_wtmp0")
                return
            # 1 <= n < 8: shift A:Y left by 1, n times.
            for _ in range(n):
                self.emit("  asl a")            # shift low; carry -> ?
                self.emit("  sta __p8c_wtmp0")
                self.emit("  tya")
                self.emit("  rol a")            # shift high through carry
                self.emit("  tay")
                self.emit("  lda __p8c_wtmp0")
            return
        # Variable shift count: loop n times.
        self._emit_word_into_wtmp(e.lhs, "__p8c_wtmp0")
        self._emit_byte_expr_into_a(e.rhs)
        self.emit("  tax")             # counter in X
        top = self._new_label("wshl_top")
        end = self._new_label("wshl_end")
        self.emit(f"  cpx #$00")
        self.emit(f"  beq {end}")
        self.emit(f"{top}:")
        self.emit("  asl __p8c_wtmp0")
        self.emit("  rol __p8c_wtmp0+1")
        self.emit("  dex")
        self.emit(f"  bne {top}")
        self.emit(f"{end}:")
        self.emit("  lda __p8c_wtmp0")
        self.emit("  ldy __p8c_wtmp0+1")

    def _emit_word_shr(self, e: BinOp) -> None:
        """uword >> n. Logical shift right."""
        if isinstance(e.rhs, IntLit) and 0 <= e.rhs.value <= 16:
            n = e.rhs.value & 0x0F
            self._emit_word_expr_into_ay(e.lhs)
            if n == 0:
                return
            if n >= 8:
                # Shift by 8: low = high, high = 0; then shift remaining.
                self.emit("  tya")            # high -> A (becomes new low)
                self.emit("  ldy #$00")       # new high = 0
                for _ in range(n - 8):
                    self.emit("  sty __p8c_wtmp0")   # for ROR
                    self.emit("  sta __p8c_wtmp0+1")
                    self.emit("  lsr __p8c_wtmp0+1")  # shift high right
                    self.emit("  ror __p8c_wtmp0")    # carry into low
                    self.emit("  lda __p8c_wtmp0")
                    self.emit("  ldy __p8c_wtmp0+1")
                return
            for _ in range(n):
                self.emit("  sty __p8c_wtmp0+1")
                self.emit("  sta __p8c_wtmp0")
                self.emit("  lsr __p8c_wtmp0+1")
                self.emit("  ror __p8c_wtmp0")
                self.emit("  lda __p8c_wtmp0")
                self.emit("  ldy __p8c_wtmp0+1")
            return
        self._emit_word_into_wtmp(e.lhs, "__p8c_wtmp0")
        self._emit_byte_expr_into_a(e.rhs)
        self.emit("  tax")
        top = self._new_label("wshr_top")
        end = self._new_label("wshr_end")
        self.emit(f"  cpx #$00")
        self.emit(f"  beq {end}")
        self.emit(f"{top}:")
        self.emit("  lsr __p8c_wtmp0+1")
        self.emit("  ror __p8c_wtmp0")
        self.emit("  dex")
        self.emit(f"  bne {top}")
        self.emit(f"{end}:")
        self.emit("  lda __p8c_wtmp0")
        self.emit("  ldy __p8c_wtmp0+1")

    def _emit_word_cmp_into_a(self, e: BinOp) -> None:
        """Compare uword LHS vs RHS, leave 1 in A if true else 0.

        Use the standard 16-bit compare idiom:
          lda lhs+1 ; cmp rhs+1 ; bne hi_diff
          lda lhs   ; cmp rhs
          hi_diff:
          ; flags now reflect a 16-bit unsigned compare.
        """
        # LHS -> wtmp0, RHS -> wtmp1, with LHS held on the CPU stack across
        # RHS evaluation so a RHS that reuses the wtmp scratch can't clobber
        # it (same nesting-safety fix as _emit_word_operands).
        self._emit_word_expr_into_ay(e.lhs)
        self.emit("  pha")                  # LHS lo
        self.emit("  tya")
        self.emit("  pha")                  # LHS hi
        self._emit_word_expr_into_ay(e.rhs)
        self.emit("  sta __p8c_wtmp1")      # RHS lo
        self.emit("  sty __p8c_wtmp1+1")    # RHS hi
        self.emit("  pla")                  # LHS hi
        self.emit("  sta __p8c_wtmp0+1")
        self.emit("  pla")                  # LHS lo
        self.emit("  sta __p8c_wtmp0")
        # 16-bit unsigned compare.
        self.emit("  lda __p8c_wtmp0+1")
        self.emit("  cmp __p8c_wtmp1+1")
        bne_lo = self._new_label("wcmp_lo")
        self.emit(f"  bne {bne_lo}")
        self.emit("  lda __p8c_wtmp0")
        self.emit("  cmp __p8c_wtmp1")
        self.emit(f"{bne_lo}:")
        # Now branch + materialize 0/1, same as the byte path.
        true_label = self._new_label("wcmp_true")
        end_label = self._new_label("wcmp_end")
        branch_taken_when_true = {
            "==": "beq", "!=": "bne",
            "<": "bcc", ">=": "bcs",
            ">": None, "<=": None,
        }[e.op]
        if branch_taken_when_true:
            self.emit(f"  {branch_taken_when_true} {true_label}")
        elif e.op == ">":
            skip = self._new_label("wcmp_skip")
            self.emit(f"  beq {skip}")
            self.emit(f"  bcs {true_label}")
            self.emit(f"{skip}:")
        else:  # "<="
            self.emit(f"  beq {true_label}")
            self.emit(f"  bcc {true_label}")
        self.emit("  lda #$00")
        self.emit(f"  jmp {end_label}")
        self.emit(f"{true_label}:")
        self.emit("  lda #$01")
        self.emit(f"{end_label}:")

    # ---- byte-expression codegen ----

    def _emit_byte_expr_into_a(self, e) -> None:
        """Evaluate a ubyte / bool expression; result is in A."""
        if isinstance(e, IntLit):
            self.emit(f"  lda #${e.value & 0xFF:02x}")
            return
        if isinstance(e, BoolLit):
            self.emit(f"  lda #${1 if e.value else 0:02x}")
            return
        if isinstance(e, Ident):
            assert e.sym is not None
            if e.sym.kind == "const":
                # Fold to immediate load.
                self.emit(f"  lda #${e.sym.const_value & 0xFF:02x}")
                return
            if e.sym.kind == "struct_instance":
                # `instance.field` read -- field_offset is set by sema.
                off = getattr(e, "field_offset", 0)
                self.emit(f"  lda {e.sym.mangled}+{off}")
                return
            assert e.sym.kind == "var"
            self.emit(f"  lda {e.sym.mangled}")
            return
        if isinstance(e, Index):
            assert e.sym is not None
            if e.sym.kind == "struct_array":
                self._emit_struct_array_index_into_y(e)
                fo = getattr(e, "field_offset", 0)
                self.emit(f"  lda {e.sym.mangled}+{fo},y")
                return
            if isinstance(e.sym.type, TUWordArray):
                # uword element read in byte context: low half only.
                self._emit_word_expr_into_ay(e.index)
                self.emit("  tay")
                self.emit(f"  lda {e.sym.mangled}_lo,y")
                return
            if self._array_fast_byte(e.sym, e.index):
                if isinstance(e.index, IntLit):
                    # constant index -> absolute address, no Y setup.
                    self.emit(f"  lda {e.sym.mangled}+{e.index.value & 0xFF}")
                    return
                self._emit_byte_expr_into_a(e.index)
                self.emit("  tay")
                self.emit(f"  lda {e.sym.mangled},y")
                return
            # ubyte element, uword index (<=256): byte-index load.
            self._emit_word_expr_into_ay(e.index)
            self.emit("  tay")
            self.emit(f"  lda {e.sym.mangled},y")
            return
        if isinstance(e, MemAt):
            if isinstance(e.addr, IntLit):
                addr = e.addr.value & 0xFFFF
                self.emit(f"  lda ${addr:04x}")
                return
            self._emit_word_expr_into_ay(e.addr)
            self.emit("  sta __p8c_ptr0")
            self.emit("  sty __p8c_ptr0+1")
            self.emit("  ldy #$00")
            self.emit("  lda (__p8c_ptr0),y")
            return
        if isinstance(e, Cast):
            # Result is a byte: the low byte of the operand in A.
            if e.operand.type is UWORD:
                self._emit_word_expr_into_ay(e.operand)   # A = low byte
            else:
                self._emit_byte_expr_into_a(e.operand)
            return
        if isinstance(e, UnaryOp):
            self._emit_byte_expr_into_a(e.operand)
            if e.op == "~":
                self.emit("  eor #$ff")
            elif e.op == "-":
                # Negate: two's complement = ~x + 1
                self.emit("  eor #$ff")
                self.emit("  clc")
                self.emit("  adc #$01")
            elif e.op == "not":
                # bool: 0 -> 1, anything else -> 0
                end = self._new_label("not_end")
                zero = self._new_label("not_zero")
                self.emit(f"  beq {zero}")
                self.emit("  lda #$00")
                self.emit(f"  jmp {end}")
                self.emit(f"{zero}:")
                self.emit("  lda #$01")
                self.emit(f"{end}:")
            else:
                raise CodeGenError(f"unknown unary op {e.op!r}")
            return
        if isinstance(e, BinOp):
            self._emit_binop_into_a(e)
            return
        if isinstance(e, Call):
            # Calls with a value: only print_ub etc. for now -- they don't
            # return values yet, so this is a TODO when we add `-> ubyte`.
            self._emit_call(e)
            return
        raise CodeGenError(
            f"codegen: cannot evaluate {type(e).__name__} as byte"
        )

    def _emit_binop_into_a(self, e: BinOp) -> None:
        cmp_ops = {"==", "!=", "<", "<=", ">", ">="}
        if e.op in cmp_ops:
            self._emit_cmp_into_a(e)
            return
        if e.op in ("and", "or"):
            self._emit_logical_into_a(e)
            return
        if e.op == "xor":
            # bool xor = bitwise xor on 0/1
            self._emit_byte_expr_into_a(e.lhs)
            self.emit("  pha")
            self._emit_byte_expr_into_a(e.rhs)
            self.emit("  sta __p8c_tmp0")
            self.emit("  pla")
            self.emit("  eor __p8c_tmp0")
            return
        # Arithmetic / bitwise / shift.
        if isinstance(e.rhs, (IntLit, Ident)):
            self._emit_byte_expr_into_a(e.lhs)
            self._emit_byte_binop_leaf(e.op, e.rhs)
            return
        # Generic (non-leaf RHS): eval LHS, hold it on the CPU stack while
        # evaluating RHS, then combine. The stack keeps LHS safe even if the
        # RHS expression reuses the tmp scratch (nested binop, indexed load,
        # ...). RHS lands in __p8c_tmp1 because the `*` helper uses tmp0 as
        # its multiplicand slot.
        self._emit_byte_expr_into_a(e.lhs)
        self.emit("  pha")
        self._emit_byte_expr_into_a(e.rhs)
        self.emit("  sta __p8c_tmp1")
        self.emit("  pla")
        self._emit_byte_binop_zp(e.op, "__p8c_tmp1")

    def _emit_byte_binop_leaf(self, op: str, rhs) -> None:
        """Emit op A, <rhs> where rhs is an IntLit or Ident (no eval needed)."""
        if isinstance(rhs, IntLit):
            operand = f"#${rhs.value & 0xFF:02x}"
        else:
            assert isinstance(rhs, Ident) and rhs.sym is not None
            operand = rhs.sym.mangled
        self._emit_byte_binop_raw(op, operand, rhs_is_immediate=isinstance(rhs, IntLit))

    def _emit_byte_binop_zp(self, op: str, zp_addr: str) -> None:
        """Emit op A, zp where zp is a zero-page address symbol."""
        self._emit_byte_binop_raw(op, zp_addr, rhs_is_immediate=False)

    def _emit_byte_binop_raw(self, op: str, operand: str, rhs_is_immediate: bool) -> None:
        if op == "+":
            self.emit("  clc")
            self.emit(f"  adc {operand}")
        elif op == "-":
            self.emit("  sec")
            self.emit(f"  sbc {operand}")
        elif op == "*":
            # ubyte * ubyte via the __p8c_mul_u8 runtime helper.
            # The helper expects multiplicand in TMP0, multiplier in TMP1,
            # returns result in A. We currently have A=LHS, so save it.
            self.emit("  sta __p8c_tmp0")
            self.emit(f"  lda {operand}")
            self.emit("  sta __p8c_tmp1")
            self.emit("  jsr __p8c_mul_u8")
            self._mul_used = True
        elif op == "&":
            self.emit(f"  and {operand}")
        elif op == "|":
            self.emit(f"  ora {operand}")
        elif op == "^":
            self.emit(f"  eor {operand}")
        elif op == "<<":
            if rhs_is_immediate:
                # operand is "#$NN" -- pull out the count for a literal
                # shift unrolled as repeated ASL.
                count = int(operand.lstrip("#$"), 16)
                for _ in range(count & 7):
                    self.emit("  asl a")
            else:
                # Variable shift count -- loop. count is in the zp slot.
                top = self._new_label("shl_top")
                end = self._new_label("shl_end")
                self.emit(f"  pha")          # save A on stack
                self.emit(f"  lda {operand}")
                self.emit(f"  tay")          # count -> Y
                self.emit(f"  pla")          # A restored
                self.emit(f"  cpy #0")
                self.emit(f"  beq {end}")
                self.emit(f"{top}:")
                self.emit(f"  asl a")
                self.emit(f"  dey")
                self.emit(f"  bne {top}")
                self.emit(f"{end}:")
        elif op == ">>":
            if rhs_is_immediate:
                count = int(operand.lstrip("#$"), 16)
                for _ in range(count & 7):
                    self.emit("  lsr a")
            else:
                top = self._new_label("shr_top")
                end = self._new_label("shr_end")
                self.emit(f"  pha")
                self.emit(f"  lda {operand}")
                self.emit(f"  tay")
                self.emit(f"  pla")
                self.emit(f"  cpy #0")
                self.emit(f"  beq {end}")
                self.emit(f"{top}:")
                self.emit(f"  lsr a")
                self.emit(f"  dey")
                self.emit(f"  bne {top}")
                self.emit(f"{end}:")
        else:
            raise CodeGenError(f"unsupported binop {op!r}")

    # ---- comparison / logical ----

    def _emit_cmp_into_a(self, e: BinOp) -> None:
        """Compare LHS vs RHS, leave 1 in A if true else 0."""
        is_signed = getattr(e, "signed", False)
        self._emit_byte_expr_into_a(e.lhs)
        self.emit("  sta __p8c_tmp0")
        self._emit_byte_expr_into_a(e.rhs)
        self.emit("  sta __p8c_tmp1")
        self.emit("  lda __p8c_tmp0")
        self._emit_cmp_value_tail(e.op, is_signed, "__p8c_tmp1")

    def _emit_cmp_value_tail(self, op: str, is_signed: bool, operand: str) -> None:
        """After lhs is in A: compare against `operand`, materialize 0/1 in A."""
        true_label = self._new_label("cmp_true")
        end_label = self._new_label("cmp_end")
        if not is_signed:
            # Unsigned compare: use CMP + standard carry/zero branches.
            self.emit(f"  cmp {operand}")
            branch = {
                "==": "beq", "!=": "bne",
                "<":  "bcc", ">=": "bcs",
                ">":  None, "<=": None,
            }[op]
            if branch is not None:
                self.emit(f"  {branch} {true_label}")
            elif op == ">":
                no = self._new_label("gt_no")
                self.emit(f"  beq {no}")
                self.emit(f"  bcs {true_label}")
                self.emit(f"{no}:")
            else:  # "<="
                self.emit(f"  beq {true_label}")
                self.emit(f"  bcc {true_label}")
        else:
            # Signed compare: SBC + overflow-corrected N flag.
            if op in ("==", "!="):
                self.emit(f"  cmp {operand}")
                self.emit(f"  {'beq' if op == '==' else 'bne'} {true_label}")
            else:
                self.emit("  sec")
                self.emit(f"  sbc {operand}")
                skip = self._new_label("sgn_ok")
                self.emit(f"  bvc {skip}")
                self.emit("  eor #$80")
                self.emit(f"{skip}:")
                # N=1 -> A<B; N=0 -> A>=B; Z=1 -> A==B.
                if op == "<":
                    self.emit(f"  bmi {true_label}")
                elif op == ">=":
                    self.emit(f"  bpl {true_label}")
                elif op == ">":
                    no = self._new_label("sgt_no")
                    self.emit(f"  beq {no}")
                    self.emit(f"  bpl {true_label}")
                    self.emit(f"{no}:")
                else:  # "<="
                    self.emit(f"  beq {true_label}")
                    self.emit(f"  bmi {true_label}")
        self.emit("  lda #$00")
        self.emit(f"  jmp {end_label}")
        self.emit(f"{true_label}:")
        self.emit("  lda #$01")
        self.emit(f"{end_label}:")

    def _emit_logical_into_a(self, e: BinOp) -> None:
        # Short-circuit `and`/`or` on bool.
        self._emit_byte_expr_into_a(e.lhs)
        if e.op == "and":
            false_label = self._new_label("and_false")
            end_label = self._new_label("and_end")
            self.emit(f"  beq {false_label}")
            self._emit_byte_expr_into_a(e.rhs)
            self.emit(f"  beq {false_label}")
            self.emit("  lda #$01")
            self.emit(f"  jmp {end_label}")
            self.emit(f"{false_label}:")
            self.emit("  lda #$00")
            self.emit(f"{end_label}:")
        else:  # or
            true_label = self._new_label("or_true")
            end_label = self._new_label("or_end")
            self.emit(f"  bne {true_label}")
            self._emit_byte_expr_into_a(e.rhs)
            self.emit(f"  bne {true_label}")
            self.emit("  lda #$00")
            self.emit(f"  jmp {end_label}")
            self.emit(f"{true_label}:")
            self.emit("  lda #$01")
            self.emit(f"{end_label}:")

    def _br(self, mnemonic: str, target: str) -> None:
        """Branch to a possibly-distant `target`.

        6502 conditional branches are signed 8-bit; we can't know the
        distance to `target` until vasm assembles. To stay safe, always
        emit the inverted-branch + JMP pattern, which costs 3 extra
        bytes but works at any distance.
        """
        inv = {
            "bne": "beq", "beq": "bne",
            "bcc": "bcs", "bcs": "bcc",
            "bmi": "bpl", "bpl": "bmi",
            "bvc": "bvs", "bvs": "bvc",
        }[mnemonic]
        skip = self._new_label("brs")
        self.emit(f"  {inv} {skip}")
        self.emit(f"  jmp {target}")
        self.emit(f"{skip}:")

    def _emit_bool_test_branch_if_false(self, cond, target: str) -> None:
        """Evaluate cond as bool, branch to `target` if FALSE."""
        self._emit_cond_branch(cond, target, jump_if_true=False)

    def _emit_cond_branch(self, cond, target: str, jump_if_true: bool) -> None:
        """Branch to `target` when cond is (jump_if_true ? true : false).

        and/or/not are short-circuited recursively -- branching per operand
        rather than materializing the whole boolean to a 0/1 byte and then
        testing it (which costs ~3x the code). Comparison leaves branch
        directly; any other expression is materialized to A and tested for
        (non)zero. The jump_if_true=False comparison/generic output is kept
        byte-identical to the previous implementation.
        """
        # not: flip the polarity.
        if isinstance(cond, UnaryOp) and cond.op == "not":
            self._emit_cond_branch(cond.operand, target, not jump_if_true)
            return
        if isinstance(cond, BinOp) and cond.op == "and":
            if jump_if_true:
                # jump iff both true: if lhs is false skip; else jump iff rhs true.
                skip = self._new_label("and_skip")
                self._emit_cond_branch(cond.lhs, skip, False)
                self._emit_cond_branch(cond.rhs, target, True)
                self.emit(f"{skip}:")
            else:
                # jump iff and is false: either operand false -> target.
                self._emit_cond_branch(cond.lhs, target, False)
                self._emit_cond_branch(cond.rhs, target, False)
            return
        if isinstance(cond, BinOp) and cond.op == "or":
            if jump_if_true:
                # jump iff either true.
                self._emit_cond_branch(cond.lhs, target, True)
                self._emit_cond_branch(cond.rhs, target, True)
            else:
                # jump iff both false: if lhs true skip; else jump iff rhs false.
                skip = self._new_label("or_skip")
                self._emit_cond_branch(cond.lhs, skip, True)
                self._emit_cond_branch(cond.rhs, target, False)
                self.emit(f"{skip}:")
            return
        if isinstance(cond, BinOp) and cond.op in {"==", "!=", "<", "<=", ">", ">="}:
            self._emit_cmp_cond(cond, target, jump_if_true)
            return
        # Generic: evaluate to A and branch on (non)zero. A uword is true iff
        # either byte is nonzero, so OR the two halves together first.
        if getattr(cond, "type", None) is UWORD:
            self._emit_word_expr_into_ay(cond)
            self.emit("  sty __p8c_tmp0")
            self.emit("  ora __p8c_tmp0")
        else:
            self._emit_byte_expr_into_a(cond)
        self._br("bne" if jump_if_true else "beq", target)

    def _emit_cmp_cond(self, cond: BinOp, target: str, jump_if_true: bool) -> None:
        """Compare cond.lhs vs cond.rhs and branch to `target` on the wanted
        truth value, without materializing a 0/1 byte."""
        is_word = (cond.lhs.type is UWORD or cond.rhs.type is UWORD)
        is_signed = getattr(cond, "signed", False)
        if is_word:
            self._emit_word_into_wtmp(cond.lhs, "__p8c_wtmp0")
            self._emit_word_into_wtmp(cond.rhs, "__p8c_wtmp1")
            self.emit("  lda __p8c_wtmp0+1")
            self.emit("  cmp __p8c_wtmp1+1")
            bne_lo = self._new_label("wcmp_lo")
            self.emit(f"  bne {bne_lo}")
            self.emit("  lda __p8c_wtmp0")
            self.emit("  cmp __p8c_wtmp1")
            self.emit(f"{bne_lo}:")
            is_signed = False  # word compare is unsigned
        else:
            operand = self._cmp_leaf_operand(cond.rhs)
            if operand is not None:
                # Leaf rhs (literal / var): no tmp0/tmp1 spill -- evaluate the
                # lhs into A and compare directly.
                self._emit_byte_expr_into_a(cond.lhs)
                if is_signed and cond.op not in ("==", "!="):
                    self.emit("  sec")
                    self.emit(f"  sbc {operand}")
                    skip = self._new_label("sgn_ok")
                    self.emit(f"  bvc {skip}")
                    self.emit("  eor #$80")
                    self.emit(f"{skip}:")
                    self._emit_cmp_branches(cond.op, target, jump_if_true, signed=True)
                    return
                self.emit(f"  cmp {operand}")
                self._emit_cmp_branches(cond.op, target, jump_if_true, signed=False)
                return
            self._emit_byte_expr_into_a(cond.lhs)
            self.emit("  sta __p8c_tmp0")
            self._emit_byte_expr_into_a(cond.rhs)
            self.emit("  sta __p8c_tmp1")
            self.emit("  lda __p8c_tmp0")
            if is_signed and cond.op not in ("==", "!="):
                # Signed compare via overflow-corrected SBC.
                self.emit("  sec")
                self.emit("  sbc __p8c_tmp1")
                skip = self._new_label("sgn_ok")
                self.emit(f"  bvc {skip}")
                self.emit("  eor #$80")
                self.emit(f"{skip}:")
                self._emit_cmp_branches(cond.op, target, jump_if_true, signed=True)
                return
            self.emit("  cmp __p8c_tmp1")
        self._emit_cmp_branches(cond.op, target, jump_if_true, signed=False)

    def _cmp_leaf_operand(self, rhs):
        """Operand string for a comparison whose rhs needs no evaluation -- a
        literal `#$XX` or a plain var's address. None otherwise (-> spill path).
        Restricted to IntLit / var Ident to match the p1 port exactly."""
        if isinstance(rhs, IntLit):
            return f"#${rhs.value & 0xFF:02x}"
        if isinstance(rhs, Ident) and rhs.sym is not None and rhs.sym.kind == "var":
            return rhs.sym.mangled
        return None

    def _emit_cmp_branches(self, op: str, target: str, jump_if_true: bool,
                           signed: bool) -> None:
        """Emit the conditional branch(es) to `target` after a CMP (unsigned)
        or overflow-corrected SBC (signed) has set the flags."""
        if not signed:
            if jump_if_true:
                direct = {"==": "beq", "!=": "bne", "<": "bcc", ">=": "bcs"}.get(op)
                if direct is not None:
                    self._br(direct, target)
                elif op == ">":
                    no = self._new_label("gt_no")
                    self.emit(f"  beq {no}")
                    self._br("bcs", target)
                    self.emit(f"{no}:")
                else:  # "<="
                    self._br("beq", target)
                    self._br("bcc", target)
            else:
                negated = {"==": "bne", "!=": "beq", "<": "bcs", ">=": "bcc"}.get(op)
                if negated is not None:
                    self._br(negated, target)
                elif op == ">":
                    self._br("beq", target)
                    self._br("bcc", target)
                else:  # "<="
                    skip = self._new_label("le_skip")
                    self.emit(f"  beq {skip}")
                    self._br("bcs", target)
                    self.emit(f"{skip}:")
            return
        # Signed: N reflects sign (Z still equality).
        if jump_if_true:
            if op == "==":
                self._br("beq", target)
            elif op == "!=":
                self._br("bne", target)
            elif op == "<":
                self._br("bmi", target)
            elif op == ">=":
                self._br("bpl", target)
            elif op == ">":
                no = self._new_label("sgt_no")
                self.emit(f"  beq {no}")
                self._br("bpl", target)
                self.emit(f"{no}:")
            else:  # "<="
                self._br("beq", target)
                self._br("bmi", target)
        else:
            if op == "==":
                self._br("bne", target)
            elif op == "!=":
                self._br("beq", target)
            elif op == "<":
                self._br("bpl", target)
            elif op == ">=":
                self._br("bmi", target)
            elif op == ">":
                self._br("beq", target)
                self._br("bmi", target)
            else:  # "<="
                skip = self._new_label("sle_skip")
                self.emit(f"  beq {skip}")
                self._br("bpl", target)
                self.emit(f"{skip}:")


    def _emit_struct_array_index_into_y(self, idx_node) -> None:
        """For `arr[i]` where arr is a struct array, compute i*struct_size
        and leave the result in Y. The struct_size comes from the array
        symbol. Uses shifts for powers of two; otherwise the mul helper."""
        struct_size = idx_node.sym.struct_size      # type: ignore[attr-defined]
        self._emit_byte_expr_into_a(idx_node.index)
        if struct_size == 1:
            self.emit("  tay")
            return
        if struct_size == 2:
            self.emit("  asl a")
            self.emit("  tay")
            return
        if struct_size == 4:
            self.emit("  asl a")
            self.emit("  asl a")
            self.emit("  tay")
            return
        if struct_size == 8:
            self.emit("  asl a")
            self.emit("  asl a")
            self.emit("  asl a")
            self.emit("  tay")
            return
        # General case: use the mul helper.
        self.emit("  sta __p8c_tmp0")
        self.emit(f"  lda #${struct_size:02x}")
        self.emit("  sta __p8c_tmp1")
        self.emit("  jsr __p8c_mul_u8")
        self.emit("  tay")
        self._mul_used = True

    # ---- plain (non-struct) array element addressing ----

    def _array_fast_byte(self, sym, index_node) -> bool:
        """True if `arr[i]` can use the tight `lda label,y` path: ubyte
        element, <=256 elements, ubyte/byte index. This is exactly the
        original codegen, so all pre-existing arrays (and their snapshot
        goldens) are unchanged."""
        return (isinstance(sym.type, TUByteArray)
                and sym.type.size <= 256
                and index_node.type in (UBYTE, BYTE))

    def _emit_addr_into_aptr(self, addr_node) -> None:
        """Compute a uword address expression into __p8c_aptr. Recognizes the
        slab form `<const_base> + <offset>` and folds the constant base into
        the final adc (index*scale + base in one pass), so peek/poke on a
        fixed-base arena are tight. The offset (`idx` for byte slabs,
        `idx << 1` for word slabs) is evaluated by the general word path, so
        the `<< 1` lowers to asl/rol as usual."""
        if (isinstance(addr_node, BinOp) and addr_node.op == "+"
                and isinstance(addr_node.lhs, IntLit)):
            base = addr_node.lhs.value & 0xFFFF
            self._emit_word_expr_into_ay(addr_node.rhs)   # offset -> A:Y
            self.emit("  clc")
            self.emit(f"  adc #<${base:04x}")
            self.emit("  sta __p8c_aptr")
            self.emit("  tya")
            self.emit(f"  adc #>${base:04x}")
            self.emit("  sta __p8c_aptr+1")
            return
        # General address: evaluate into A:Y, then park in the pointer.
        self._emit_word_expr_into_ay(addr_node)
        self.emit("  sta __p8c_aptr")
        self.emit("  sty __p8c_aptr+1")

    def _emit_regabi_args(self, args, params) -> None:
        """Load each call arg into its annotated register (A / X / Y / AY).
        X/Y-bound args go first (evaluated via A, then transferred); the
        A/AY-bound arg goes LAST so the evaluator's use of A doesn't clobber
        an already-loaded register."""
        order = sorted(range(len(args)),
                       key=lambda k: params[k].reg in ("A", "AY"))
        for k in order:
            arg, reg = args[k], params[k].reg
            if reg == "A":
                self._emit_byte_expr_into_a(arg)
            elif reg == "AY":
                self._emit_word_expr_into_ay(arg)
            elif reg == "X":
                self._emit_byte_expr_into_a(arg)
                self.emit("  tax")
            elif reg == "Y":
                self._emit_byte_expr_into_a(arg)
                self.emit("  tay")
            else:
                raise CodeGenError(f"unsupported arg register {reg!r}")

    def _emit_call(self, c: Call) -> None:
        sym = c.sym
        assert sym is not None
        if sym.kind in ("sub", "asmsub"):
            target = next(
                (s for s in self.prog.subs if s.name == sym.name), None
            )
            params = target.params if target else []
            # asmsub call ABI (for the simple cases we model in v0):
            #   no args: just jsr.
            #   1 ubyte arg: load into A, jsr.
            #   1 uword arg: load into A:Y, jsr.
            #   any other shape: caller must use a %asm{{...}} wrapper.
            # Per upstream Prog8, ubyte returns in A and uword in A:Y.
            if sym.kind == "asmsub":
                # Register-ABI: a sub whose params carry @REG annotations takes
                # its args in the named registers (A / X / Y / AY); JSR the
                # address (= $ADDR / extsub) or the body label.
                if params and all(p.reg for p in params):
                    self._emit_regabi_args(c.args, params)
                elif len(c.args) == 0:
                    pass
                elif len(c.args) == 1:
                    pt = type_from_name(params[0].type_name)
                    if pt is UBYTE:
                        self._emit_byte_expr_into_a(c.args[0])
                    else:
                        self._emit_word_expr_into_ay(c.args[0])
                else:
                    raise CodeGenError(
                        f"asmsub {sym.name!r}: multi-arg calls need @REG "
                        f"annotations, or wrap with %asm{{{{ ... }}}} instead"
                    )
                self.emit(f"  jsr {sym.asm_target or sym.mangled}")
                return
            # Regular sub: pass args via the callee's static param slots.
            # Single arg: store it straight into the slot after evaluating it
            # (nothing else writes the slot between the store and the JSR, so
            # there is no reentrancy hazard even if the arg's own evaluation
            # called this sub). This is the common case (out_text, etc.) and
            # avoids the push/pop dance.
            if len(c.args) == 1 and target is not None and not target.is_inline:
                p = params[0]
                pt = type_from_name(p.type_name)
                if pt is UBYTE:
                    self._emit_byte_expr_into_a(c.args[0])
                    self.emit(f"  sta {p.sym.mangled}")
                else:
                    self._emit_word_expr_into_ay(c.args[0])
                    self.emit(f"  sta {p.sym.mangled}")
                    self.emit(f"  sty {p.sym.mangled}+1")
                self.emit(f"  jsr {sym.mangled}")
                return
            # Multiple args: param slots are NOT reentrant, so we must not write
            # one while a later argument is still being evaluated -- that
            # argument's evaluation may itself call this (or a transitively
            # shared) sub and clobber the slots. So evaluate every argument
            # onto the hardware stack first, then pop them into the param
            # slots immediately before the JSR.
            arg_slots = []   # (param sym, is_word) in arg order
            for arg, p in zip(c.args, params):
                if p.sym is None:
                    raise CodeGenError(f"param {p.name!r} not resolved by sema")
                pt = type_from_name(p.type_name)
                if pt is UBYTE:
                    self._emit_byte_expr_into_a(arg)
                    self.emit("  pha")
                    arg_slots.append((p.sym, False))
                else:
                    self._emit_word_expr_into_ay(arg)
                    self.emit("  pha")            # low
                    self.emit("  tya")
                    self.emit("  pha")            # high
                    arg_slots.append((p.sym, True))
            for p_sym, is_word in reversed(arg_slots):
                if is_word:
                    self.emit("  pla")            # high
                    self.emit(f"  sta {p_sym.mangled}+1")
                    self.emit("  pla")            # low
                    self.emit(f"  sta {p_sym.mangled}")
                else:
                    self.emit("  pla")
                    self.emit(f"  sta {p_sym.mangled}")
            # Inline sub: splice the body in place instead of JSR.
            if target is not None and target.is_inline:
                # Save the caller's return label (each inline-call gets
                # its own per-site epilogue so `return` jumps locally).
                saved_ret = self._return_label
                saved_sub = self._current_sub
                self._return_label = self._new_label(f"inline_{target.name}_ret")
                self._current_sub = target
                self._emit_block(target.body)
                self.emit(f"{self._return_label}:")
                self._current_sub = saved_sub
                self._return_label = saved_ret
                return
            self.emit(f"  jsr {sym.mangled}")
            return

        if sym.kind == "extsub":
            target = sym.asm_target
            if not target:
                raise CodeGenError(f"extsub {sym.name!r} has no asm_target")
            if target == "display_string":
                if len(c.args) != 1 or not isinstance(c.args[0], StrLit):
                    raise CodeGenError(
                        "txt.print expects exactly one string literal"
                    )
                lit: StrLit = c.args[0]
                lbl = self._str_label(lit)
                self.emit(f"  lda #<{lbl}")
                self.emit(f"  ldx #>{lbl}")
                self.emit(f"  jsr {target}")
                return
            if target == "clear_display":
                if c.args:
                    raise CodeGenError("lcd.clear takes no arguments")
                self.emit(f"  jsr {target}")
                return
            if target == "display_hex":
                # txt.print_ub(byte) -- print byte as 2 hex chars.
                if len(c.args) != 1:
                    raise CodeGenError("txt.print_ub expects exactly one arg")
                self._emit_byte_expr_into_a(c.args[0])
                self.emit(f"  jsr {target}")
                return
            if target == "__p8c_print_uw":
                # txt.print_uw(uw) -- print 4 hex chars (high byte first).
                if len(c.args) != 1:
                    raise CodeGenError("txt.print_uw expects exactly one arg")
                self._emit_word_expr_into_ay(c.args[0])
                self.emit("  pha")                 # save low byte
                self.emit("  tya")                 # high byte -> A
                self.emit("  jsr display_hex")
                self.emit("  pla")                 # restore low byte
                self.emit("  jsr display_hex")
                return
            raise CodeGenError(f"unknown extsub target {target!r}")

        if sym.kind == "builtin":
            return self._emit_builtin_call(c)

        raise CodeGenError(f"call kind {sym.kind!r} not implemented")

    def _emit_builtin_call(self, c: Call) -> None:
        """Lower a builtin call (peek/poke/lsb/msb/...) to inline asm."""
        name = c.sym.name
        if name == "compare":
            # strings.compare(a, b): both args are uword addresses. Park them
            # in the two ZP word pointers, then jsr the shared helper (result
            # -1/0/1 in A). Stack-shuffle the first pointer so evaluating the
            # second arg can't clobber it.
            if len(c.args) != 2:
                raise CodeGenError("strings.compare takes 2 args")
            self._emit_word_expr_into_ay(c.args[0])
            self.emit("  pha")
            self.emit("  tya")
            self.emit("  pha")
            self._emit_word_expr_into_ay(c.args[1])
            self.emit("  sta __p8c_wtmp1")
            self.emit("  sty __p8c_wtmp1+1")
            self.emit("  pla")
            self.emit("  sta __p8c_wtmp0+1")
            self.emit("  pla")
            self.emit("  sta __p8c_wtmp0")
            self.emit("  jsr __p8c_strcmp")
            self._strcmp_used = True
            return
        if name == "peek":
            if len(c.args) != 1:
                raise CodeGenError("peek expects one address argument")
            if isinstance(c.args[0], IntLit):
                addr = c.args[0].value & 0xFFFF
                self.emit(f"  lda ${addr:04x}")
                return
            # Computed address: park it in __p8c_aptr, then lda (aptr),y.
            self._emit_addr_into_aptr(c.args[0])
            self.emit("  ldy #$00")
            self.emit("  lda (__p8c_aptr),y")
            return
        if name == "poke":
            if len(c.args) != 2:
                raise CodeGenError("poke expects (address, byte_expr)")
            if isinstance(c.args[0], IntLit):
                addr = c.args[0].value & 0xFFFF
                self._emit_byte_expr_into_a(c.args[1])
                self.emit(f"  sta ${addr:04x}")
                return
            # Computed address: eval value first (stash on stack), then the
            # address into __p8c_aptr, then store.
            self._emit_byte_expr_into_a(c.args[1])
            self.emit("  pha")
            self._emit_addr_into_aptr(c.args[0])
            self.emit("  pla")
            self.emit("  ldy #$00")
            self.emit("  sta (__p8c_aptr),y")
            return
        if name == "peekw":
            if len(c.args) != 1:
                raise CodeGenError("peekw expects one address argument")
            self._emit_addr_into_aptr(c.args[0])
            self.emit("  ldy #$00")
            self.emit("  lda (__p8c_aptr),y")   # lo
            self.emit("  pha")
            self.emit("  ldy #$01")
            self.emit("  lda (__p8c_aptr),y")   # hi
            self.emit("  tay")
            self.emit("  pla")                  # lo -> A, hi in Y
            return
        if name == "pokew":
            if len(c.args) != 2:
                raise CodeGenError("pokew expects (address, word_expr)")
            self._emit_word_expr_into_ay(c.args[1])   # value lo=A, hi=Y
            self.emit("  pha")               # lo
            self.emit("  tya")
            self.emit("  pha")               # hi
            self._emit_addr_into_aptr(c.args[0])      # address
            self.emit("  pla")               # hi
            self.emit("  ldy #$01")
            self.emit("  sta (__p8c_aptr),y")
            self.emit("  pla")               # lo
            self.emit("  ldy #$00")
            self.emit("  sta (__p8c_aptr),y")
            return
        if name == "lsb":
            # lsb(uword) -> ubyte: just the low byte.
            if len(c.args) != 1:
                raise CodeGenError("lsb takes 1 arg")
            self._emit_word_expr_into_ay(c.args[0])
            # Low byte already in A; discard Y.
            return
        if name == "msb":
            if len(c.args) != 1:
                raise CodeGenError("msb takes 1 arg")
            self._emit_word_expr_into_ay(c.args[0])
            self.emit("  tya")
            return
        if name == "mkword":
            # mkword(msb_byte, lsb_byte) -> uword, result lo in A, hi in Y.
            if len(c.args) != 2:
                raise CodeGenError("mkword takes 2 args (msb, lsb)")
            # The high byte can't simply live in Y across the low-byte
            # evaluation: an array read (or any Y-using expr) on the low
            # side would clobber it. Hold the high byte on the stack and
            # shuffle through X at the end so A=low, Y=high regardless.
            self._emit_byte_expr_into_a(c.args[0])  # high byte
            self.emit("  pha")
            self._emit_byte_expr_into_a(c.args[1])  # low byte
            self.emit("  tax")            # low -> X
            self.emit("  pla")            # high -> A
            self.emit("  tay")            # high -> Y
            self.emit("  txa")            # low -> A
            return
        if name == "len":
            # len(arr) -- compile-time array length as a ubyte literal.
            if len(c.args) != 1 or not isinstance(c.args[0], Ident):
                raise CodeGenError("len takes one array identifier")
            sym = c.args[0].sym
            if sym is None or sym.kind != "array":
                raise CodeGenError("len(): arg must be an array")
            sz = sym.type.size & 0xFF
            self.emit(f"  lda #${sz:02x}")
            return
        if name == "sizeof":
            # sizeof(name) -- bytes occupied by an identifier (compile-time).
            if len(c.args) != 1 or not isinstance(c.args[0], Ident):
                raise CodeGenError("sizeof takes one identifier")
            sym = c.args[0].sym
            if sym is None:
                raise CodeGenError("sizeof: unknown symbol")
            if sym.kind == "array":
                sz = sym.type.size & 0xFF
            elif sym.type is UBYTE:
                sz = 1
            elif sym.type is UWORD:
                sz = 2
            else:
                raise CodeGenError(f"sizeof({c.args[0].name!r}): unknown size")
            self.emit(f"  lda #${sz:02x}")
            return
        raise CodeGenError(f"unknown builtin {name!r}")


def _aug_to_op(aug: str) -> str:
    """Map an augmented operator to its plain op."""
    return {
        "+=": "+", "-=": "-", "&=": "&", "|=": "|", "^=": "^",
        "<<=": "<<", ">>=": ">>",
    }[aug]


def generate(prog: Program, source_path: str) -> str:
    return CodeGen(prog, source_path).generate()
