#!/usr/bin/env python3
"""Firmware golden manifest: prove a refactor leaves every binary byte-identical.

Assembles every *.s / *.asm under --root (skipping --exclude dirs) with vasm,
once with the RAM-upload flags (-esc, as compile_and_upload*.sh) and once with
the EEPROM flags (no -esc, as compile_and_program.sh), and records the sha256
of each output -- or FAIL if it does not assemble.

  firmware_manifest.py update   # (re)write the manifest from the current tree
  firmware_manifest.py check    # rebuild and compare; exit 1 on any difference

The manifest also records the vasm version. check only warns if the vasm on
PATH differs but every hash still matches (vasm 1.9f and 2.0-2.0f all give
identical binaries); if hashes differ too, it names the version as a suspect.

Each source is assembled from its own directory, as the upload scripts do,
so relative .include paths resolve the same way. --include adds -I dirs.
"""
import argparse
import hashlib
import os
import subprocess
import sys
import tempfile

VASM = 'vasm6502_oldstyle'
BASE_FLAGS = ['-quiet', '-wdc02', '-wfail', '-Fbin', '-dotdir', '-ignore-mult-inc']
FLAG_SETS = [('esc', ['-esc']), ('noesc', [])]
DEFAULT_EXCLUDES = ['attic', 'emulator', 'toolchain', '.git']
HEADER = ('# Firmware golden manifest -- generated by tools/firmware_manifest.py update\n'
          '# <source>  esc=<sha256|FAIL>  noesc=<sha256|FAIL>\n')


def find_sources(root, excludes):
    excluded = {os.path.normpath(e) for e in excludes}
    sources = []
    for dirpath, dirnames, filenames in os.walk(root):
        rel_dir = os.path.relpath(dirpath, root)
        dirnames[:] = sorted(d for d in dirnames
                             if os.path.normpath(os.path.join(rel_dir, d)) not in excluded
                             and d not in excluded)
        for name in filenames:
            if name.endswith(('.s', '.asm')):
                sources.append(os.path.normpath(os.path.join(rel_dir, name)))
    return sorted(sources)


def assemble(root, source, flags, includes):
    path = os.path.join(root, source)
    with tempfile.TemporaryDirectory() as tmp:
        out = os.path.join(tmp, 'a.out')
        cmd = [VASM, *BASE_FLAGS, *flags,
               *('-I' + os.path.abspath(os.path.join(root, i)) for i in includes),
               '-o', out, os.path.basename(path)]
        result = subprocess.run(cmd, cwd=os.path.dirname(path),
                                stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        if result.returncode != 0 or not os.path.exists(out):
            return 'FAIL'
        with open(out, 'rb') as f:
            return hashlib.sha256(f.read()).hexdigest()


def read_include_list(path):
    with open(path) as f:
        return [l.strip() for l in f if l.strip() and not l.lstrip().startswith('#')]


def build(root, excludes, includes):
    return {src: [f'{name}={assemble(root, src, flags, includes)}'
                  for name, flags in FLAG_SETS]
            for src in find_sources(root, excludes)}


ASSEMBLER_PREFIX = '# assembler: '


def read_assembler(path):
    with open(path) as f:
        for line in f:
            if line.startswith(ASSEMBLER_PREFIX):
                return line[len(ASSEMBLER_PREFIX):].strip()
    return None


def read_manifest(path):
    entries = {}
    with open(path) as f:
        for line in f:
            if line.strip() and not line.startswith('#'):
                fields = line.split()
                entries[fields[0]] = fields[1:]
    return entries


def vasm_version():
    result = subprocess.run([VASM], stdin=subprocess.DEVNULL, capture_output=True, text=True)
    lines = (result.stdout + result.stderr).splitlines()
    return lines[0].strip() if lines else 'unknown'


def write_manifest(path, entries):
    with open(path, 'w') as f:
        f.write(HEADER)
        f.write(f'{ASSEMBLER_PREFIX}{vasm_version()}\n')
        for src in sorted(entries):
            f.write(' '.join([src, *entries[src]]) + '\n')


def compare(expected, actual):
    problems = []
    for src in sorted(set(expected) | set(actual)):
        if src not in actual:
            problems.append(f'missing:  {src}')
        elif src not in expected:
            problems.append(f'new:      {src}  {" ".join(actual[src])}')
        elif expected[src] != actual[src]:
            problems.append(f'changed:  {src}  {" ".join(expected[src])}  ->  {" ".join(actual[src])}')
    return problems


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('command', choices=['update', 'check'])
    parser.add_argument('--root', default='.')
    parser.add_argument('--manifest', default='firmware/manifest.txt')
    parser.add_argument('--exclude', action='append',
                        help=f'directory to skip, relative to root (default: {DEFAULT_EXCLUDES})')
    parser.add_argument('--include', action='append', default=[],
                        help='extra vasm -I directory, relative to root')
    parser.add_argument('--include-list',
                        help='file listing vasm -I directories (relative to root), one per line')
    args = parser.parse_args(argv)
    excludes = args.exclude if args.exclude is not None else DEFAULT_EXCLUDES
    if args.include_list:
        args.include += read_include_list(args.include_list)

    actual = build(args.root, excludes, args.include)
    if args.command == 'update':
        write_manifest(args.manifest, actual)
        fails = sum('FAIL' in ' '.join(v) for v in actual.values())
        print(f'{len(actual)} sources recorded ({fails} with a FAIL entry) in {args.manifest}')
        return 0

    if not os.path.exists(args.manifest):
        print(f'no manifest at {args.manifest}; run "update" first')
        return 1
    problems = compare(read_manifest(args.manifest), actual)
    # Matching hashes are the real test, so a different vasm only fails the
    # check if it also changes the output; either way it is reported
    recorded, current = read_assembler(args.manifest), vasm_version()
    if recorded != current:
        note = f'assembler differs: manifest has "{recorded}", PATH has "{current}"'
        print(f'{note} -- which may explain the differences below' if problems
              else f'warning: {note} -- all hashes match')
    for p in problems:
        print(p)
    print(f'{len(actual)} sources checked, {len(problems)} differences')
    return 1 if problems else 0


if __name__ == '__main__':
    sys.exit(main())
