#!/usr/bin/env python3
"""Michael's 12x16 font. Its glyphs come from the original C font, firmware/fonts/font-12x16.c (the array
console_font_12x16: 256 glyphs of 16 rows, 2 bytes a row, the leftmost pixel in the first byte's top bit, in
the PC's code page 437 order): those for $20-$FF, as they are. Another font in the same format can take its
place (C_FONT, ARRAY).

They're expanded into firmware/lib/graphics/font_12x16.txt, the view (UTF-8): each glyph a line naming it as
code page 437 has it ("$21 '!'", "$7f '⌂'", "$80 'Ç'") then 16 rows of 12 pixels, '#' lit and '.' dark, the top
row first. Everything else is generated from the view: the firmware's table has $20-$7F (Michael's graphics
driver draws no more), the FPGA's memory every code, the control codes blank (text mode drops them).

  font_12x16.py              rewrites the view, firmware/lib/graphics/character_patterns_12x16.inc (the
                             firmware's table) and emulator/chips/font_12x16.h (the emulator's, for the FPGA's
                             text mode), all committed, as the firmware and emulator builds run no tools
  font_12x16.py vh PATH      writes the FPGA's font memory, as Verilog that fills an array `font` (the FPGA
                             builds run this)

Each stores a glyph a column at a time, left to right, as Michael's driver sends it (gd_show_character): the
column's 16 pixels, the top one first. The firmware's table has 2 bytes a column (rows 0-7, then 8-15, the
top row in bit 0); the FPGA's memory and the emulator's table a 16-bit word a column (the top row in bit 0),
the FPGA's at (code << 4) | column, the emulator's at [code][column].
"""
import os
import re
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
C_FONT = os.path.join(ROOT, 'firmware', 'fonts', 'font-12x16.c')
ARRAY = 'console_font_12x16'
DEL = 0x7F
GRAPHICS = os.path.join(ROOT, 'firmware', 'lib', 'graphics')
SOURCE = os.path.join(GRAPHICS, 'font_12x16.txt')   # the view
INC = os.path.join(GRAPHICS, 'character_patterns_12x16.inc')
HEADER = os.path.join(ROOT, 'emulator', 'chips', 'font_12x16.h')
WIDTH, HEIGHT = 12, 16
CODES = range(0x20, 0x100)   # the view's


def read_c_font(path=C_FONT, array=ARRAY):
    """{code: [16 rows of 12 '#'/'.']} for every glyph of the C font's array"""
    with open(path) as f:
        text = re.sub(r'/\*.*?\*/', '', f.read(), flags=re.S)   # comments show the pixels too, and "hex=0x01"
    body = re.search(r'\b' + array + r'\s*\[\s*\]\s*=\s*\{(.*?)\}', text, re.S)[1]
    data = [int(b, 16) for b in re.findall(r'0x([0-9a-fA-F]{2})', body)]
    rows = [format(data[i] << 8 | data[i + 1], '016b')[:WIDTH].replace('1', '#').replace('0', '.')
            for i in range(0, len(data), 2)]
    return {code: rows[code * HEIGHT:(code + 1) * HEIGHT] for code in range(len(rows) // HEIGHT)}


def build():
    """The font: the C font's glyphs from $20 up"""
    c_font = read_c_font()
    return {code: c_font[code] for code in CODES}


def name(code):
    """As code page 437 shows the code (Python's codec has DEL as the control code)"""
    return "'⌂'" if code == DEL else f"'{bytes([code]).decode('cp437')}'"


def view(glyphs):
    lines = ['# Generated by tools/font_12x16.py, do not edit: Michael\'s 12x16 font, the glyphs of the C font',
             f'# {os.path.relpath(C_FONT, ROOT)} ({ARRAY}) from $20 up. Each glyph is a line naming it, as code page',
             "# 437 has it, then 16 rows of 12 pixels, '#' lit and '.' dark, the top row first."]
    for code in sorted(glyphs):
        lines += ['', f'${code:02x} {name(code)}'] + glyphs[code]
    return '\n'.join(lines) + '\n'


def read_source(path=SOURCE):
    """{code: [16 rows of 12 '#'/'.']} from the view"""
    glyphs, rows = {}, None
    with open(path, encoding='utf-8') as f:
        for line in f:
            line = line.rstrip('\n')
            if not line or line.startswith('# '):
                continue
            m = re.match(r"\$([0-9a-f]{2}) '.'$", line)
            if m:
                rows = glyphs[int(m[1], 16)] = []
            else:
                rows.append(line)
    return glyphs


def columns(rows):
    """The glyph's columns as 16-bit words, the top row in bit 0."""
    return [sum(1 << y for y in range(HEIGHT) if rows[y][x] == '#') for x in range(WIDTH)]


def firmware_table(glyphs):
    lines = ['character_patterns_12x16:']
    for code in sorted(c for c in glyphs if c <= DEL):   # what Michael's graphics driver draws
        data = [b for word in columns(glyphs[code]) for b in (word & 0xFF, word >> 8)]
        named = 'DEL' if code == DEL else f"'{chr(code)}'"   # ASCII, for the assemblers
        lines.append('  .byte ' + ', '.join(f'${b:02x}' for b in data) + f" ; {code:3d} ${code:02x} {named}")
    return '\n'.join(lines) + '\n'


def fpga_words(glyphs):
    """256 codes of 16 words: the glyph's columns, then padding; the control codes (no glyph) blank."""
    words = [0] * (256 * 16)
    for code, rows in glyphs.items():
        for x, word in enumerate(columns(rows)):
            words[(code << 4) | x] = word
    return words


def fpga_include(glyphs):
    lines = ['// Generated by tools/font_12x16.py from firmware/lib/graphics/font_12x16.txt: do not edit.',
             '// Fills `font`, (code << 4) | column, a column\'s 16 pixels with the top one in bit 0.']
    lines += [f"    font[{i}] = 16'h{w:04X};" for i, w in enumerate(fpga_words(glyphs))]   # every word: no loop to zero
    return '\n'.join(lines) + '\n'


def emulator_header(glyphs):
    """The FPGA's words as a C table, font_12x16[code][column], for the emulator's model of text mode."""
    words = fpga_words(glyphs)
    lines = ['/* Generated by tools/font_12x16.py from firmware/lib/graphics/font_12x16.txt: do not edit.',
             ' * Michael\'s 12x16 font as the FPGA\'s text mode has it: font_12x16[code][column] is the column\'s 16',
             ' * pixels, the top one in bit 0. The control codes (text mode drops them) are blank. */',
             '#ifndef EMULATOR_CHIPS_FONT_12X16_H', '#define EMULATOR_CHIPS_FONT_12X16_H', '',
             '#include <stdint.h>', '', f'static const uint16_t font_12x16[256][{WIDTH}] = {{']
    for code in range(256):
        named = f' {name(code)}' if code in glyphs else ''
        columns = ', '.join(f'0x{w:04X}' for w in words[code << 4:(code << 4) + WIDTH])
        lines.append(f'    /* ${code:02X}{named} */ {{ {columns} }},')
    lines += ['};', '', '#endif']
    return '\n'.join(lines) + '\n'


def write(path, text):
    os.makedirs(os.path.dirname(os.path.abspath(path)), exist_ok=True)
    with open(path, 'w', encoding='utf-8') as f:
        f.write(text)


def main():
    if len(sys.argv) == 1:
        write(SOURCE, view(build()))
        write(INC, firmware_table(read_source()))
        write(HEADER, emulator_header(read_source()))
    elif len(sys.argv) == 3 and sys.argv[1] == 'vh':
        write(sys.argv[2], fpga_include(read_source()))
    else:
        sys.exit(__doc__)


if __name__ == '__main__':
    main()
