#!/usr/bin/env python3
"""Michael's 12x16 font, from its one source: firmware/lib/graphics/font_12x16.txt, each glyph a line naming
it ("$21 '!'") then 16 rows of 12 pixels, '#' lit and '.' dark, the top row first.

  font_12x16.py inc          rewrites firmware/lib/graphics/character_patterns_12x16.inc, the firmware's table
  font_12x16.py vh PATH      writes the FPGA's font memory, as Verilog that fills an array `font` (the FPGA
                             builds run this)

Both store a glyph a column at a time, left to right, as Michael's driver sends it (gd_show_character): the
column's 16 pixels, the top one first. The firmware's table has 2 bytes a column (rows 0-7, then 8-15, the
top row in bit 0); the FPGA's memory a 16-bit word a column, at (code << 4) | column.
"""
import os
import re
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
SOURCE = os.path.join(ROOT, 'firmware', 'lib', 'graphics', 'font_12x16.txt')
INC = os.path.join(ROOT, 'firmware', 'lib', 'graphics', 'character_patterns_12x16.inc')
WIDTH, HEIGHT = 12, 16


def read_source(path=SOURCE):
    """{code: [16 rows of 12 '#'/'.']}"""
    glyphs, rows = {}, None
    with open(path) as f:
        for line in f:
            line = line.rstrip('\n')
            if not line or line.startswith('# '):
                continue
            m = re.match(r"\$([0-9a-f]{2}) '.'$", line)
            if m:
                rows = glyphs[int(m[1], 16)] = []
            else:
                rows.append(line)
    return glyphs


def columns(rows):
    """The glyph's columns as 16-bit words, the top row in bit 0."""
    return [sum(1 << y for y in range(HEIGHT) if rows[y][x] == '#') for x in range(WIDTH)]


def firmware_table(glyphs):
    lines = ['character_patterns_12x16:']
    for code in sorted(glyphs):
        data = [b for word in columns(glyphs[code]) for b in (word & 0xFF, word >> 8)]
        lines.append('  .byte ' + ', '.join(f'${b:02x}' for b in data) + f" ; {code:3d} ${code:02x} '{chr(code)}'")
    return '\n'.join(lines) + '\n'


def fpga_words(glyphs):
    """128 codes of 16 words: the glyph's columns, then padding; codes without a glyph are blank."""
    words = [0] * (128 * 16)
    for code, rows in glyphs.items():
        for x, word in enumerate(columns(rows)):
            words[(code << 4) | x] = word
    return words


def fpga_include(glyphs):
    lines = ['// Generated by tools/font_12x16.py from firmware/lib/graphics/font_12x16.txt: do not edit.',
             '// Fills `font`, (code << 4) | column, a column\'s 16 pixels with the top one in bit 0.']
    lines += [f"    font[{i}] = 16'h{w:04X};" for i, w in enumerate(fpga_words(glyphs))]   # every word: no loop to zero
    return '\n'.join(lines) + '\n'


def main():
    if len(sys.argv) == 2 and sys.argv[1] == 'inc':
        path, text = INC, firmware_table(read_source())
    elif len(sys.argv) == 3 and sys.argv[1] == 'vh':
        path, text = sys.argv[2], fpga_include(read_source())
    else:
        sys.exit(__doc__)
    os.makedirs(os.path.dirname(os.path.abspath(path)), exist_ok=True)
    with open(path, 'w') as f:
        f.write(text)


if __name__ == '__main__':
    main()
